In [14]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch import nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
import math
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
import scipy.optimize as opt
import torch.distributions as dist
from sklearn.metrics import accuracy_score
import warnings
from tqdm.notebook import tqdm_notebook as tqdm
from collections import defaultdict

In [15]:
warnings.filterwarnings('ignore')

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

超参数设置

In [17]:
# 超参数
tem = 0.02
bs = 128
seed = 5009
epochs = 1
epoch_online=1
sample_interval = 2000
flip_percent = 0.2

## 加载数据集

In [18]:
def get_dataset():
    train_data=pd.read_csv('en_KDDTrain+.csv')
    test_data=pd.read_csv('en_KDDTest+.csv')
    y_train=train_data['label2']
    y_test=test_data['label2']
    X_train=train_data.drop(columns=['label2','class','label'])
    X_test=test_data.drop(columns=['label2','class','label'])
    normalize=MinMaxScaler()
    X_train=normalize.fit_transform(X_train)
    X_test=normalize.fit_transform(X_test)
    return X_train,y_train,X_test,y_test

In [19]:
x_train,y_train,x_test,y_test=get_dataset()
# 转换为torch张量
x_train,y_train=torch.FloatTensor(x_train).to(device),torch.LongTensor(y_train).to(device)
x_test,y_test=torch.FloatTensor(x_test).to(device),torch.LongTensor(y_test).to(device)

In [20]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

(torch.Size([125973, 121]),
 torch.Size([125973]),
 torch.Size([22544, 121]),
 torch.Size([22544]))

In [21]:
def evaluate(y,y_pred):
    y= y.cpu().detach().numpy()
    y_pred= y_pred.cpu().detach().numpy()
    # 混淆矩阵
    print("Confusion matrix")
    print(confusion_matrix(y, y_pred))
    # Accuracy 
    print('Accuracy ',accuracy_score(y, y_pred))
    # Precision 
    print('Precision ',precision_score(y, y_pred))
    # Recall
    print('Recall ',recall_score(y, y_pred))
    # F1 score
    print('F1 score ',f1_score(y,y_pred))

## 加载模型

AE自编码器模块

In [22]:
class AE(nn.Module):
    def __init__(self, input_dim):
        super(AE, self).__init__()
        # 计算输入维度的最近的2的幂次方，比如输入维度是206，则最近的2的幂次方是128
        nearest_power_of_2 = 2 ** round(math.log2(input_dim))
        
        second_fourth_layer_size = nearest_power_of_2 // 2
        third_layer_size = nearest_power_of_2 // 4
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, third_layer_size)
        )
        self.decoder = nn.Sequential(
            nn.ReLU(),
            nn.Linear(third_layer_size, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, input_dim)
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

CRC对比损失模块

In [23]:
class CRCLoss(nn.Module):
    def __init__(self, device, temperature=0.1, scale_by_temperature=True):
        super(CRCLoss, self).__init__()
        self.device = device
        self.temperature = temperature
        self.scale_by_temperature = scale_by_temperature

    def forward(self, features, labels=None):
        # 计算特征的归一化表示
        features = F.normalize(features, p=2, dim=1)
        batch_size = features.shape[0]
        num_norm = len(labels==0)
        ## contiguous方法确保张量在内存是连续存储的，因为变换视图操作需要确保张量在内存中是连续存储的
        labels = labels.contiguous().view(-1, 1) # batch_size * 1
        
        if labels.shape[0] != batch_size:
            raise ValueError('Batch size of features and labels do not match.')
        
        # 计算余弦相似度，cosine_sim[i][j]表示features[i]和features[j]的余弦相似度，矩阵大小为batch_size * batch_size
        cosine_sim = torch.nn.functional.cosine_similarity(features.unsqueeze(1), features.unsqueeze(0), dim = -1)/self.temperature
        # 将余弦相似度的对角线元素设置为0
        mask_diag = torch.eye(batch_size, dtype=torch.bool)
        cosine_sim[mask_diag] = 0
        # 正样本对
        sim_pos = cosine_sim[(labels==0).squeeze()]
        # 正样本对间的余弦相似度
        sim_pos_pos = sim_pos[:,(labels==0).squeeze()] 
        # 正样本与负样本间的余弦相似度
        sim_pos_neg = sim_pos[:,(labels==1).squeeze()]
        # 计算正样本与负样本间的分数和
        sum_pos_neg = torch.sum(torch.exp(sim_pos_neg))
        # 计算分母
        denominator = torch.exp(sim_pos_pos) + sum_pos_neg       
        loss = -(sim_pos_pos-torch.log(denominator))  
        
        
        if self.scale_by_temperature:
            loss = loss * self.temperature
        # 计算损失
        loss= loss.mean()
        return loss

## ADM自主决策

In [24]:
def gaussian_pdf(x, mean, std):
    pdf = 1/(std*np.sqrt(2*np.pi))*np.exp(-(x-mean)**2/(2*std**2))
    return pdf
def log_likelihood(params,data):
    data = data.cpu().detach().numpy()
    mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc = params
    pdf1 = gaussian_pdf(data, mean_pos_enc, std_pos_enc)
    pdf2 = gaussian_pdf(data, mean_neg_enc, std_neg_enc)
    mixture_pdf = 0.5*pdf1 + 0.5*pdf2
    log_likelihood = -np.sum(np.log(mixture_pdf))
    
    return log_likelihood
def predict(norm_enc, norm_dec, x_train, y_train, x_test, model):
    x_train_pos=x_train[(y_train==0).squeeze()]
    x_train_neg=x_train[(y_train==1).squeeze()]
    
    # 训练集全体样本编码和解码特征
    train_enc = F.normalize(model(x_train)[0], p=2, dim=1)
    train_dec = F.normalize(model(x_train)[1], p=2, dim=1)
    # 训练集正样本编码和解码特征
    train_enc_pos = F.normalize(model(x_train_pos)[0], p=2, dim=1)
    train_dec_pos = F.normalize(model(x_train_pos)[1], p=2, dim=1)
    # 训练集负样本编码和解码特征
    train_enc_neg = F.normalize(model(x_train_neg)[0], p=2, dim=1)
    train_dec_neg = F.normalize(model(x_train_neg)[1], p=2, dim=1)
    
    # 分别计算训练集正样本特征和平均正样本特征的余弦相似度 负样本同理 全体样本同理 
    sim_pos_norm_enc = F.cosine_similarity(train_enc_pos, norm_enc.unsqueeze(0), dim=1) 
    sim_pos_norm_dec = F.cosine_similarity(train_dec_pos, norm_dec.unsqueeze(0), dim=1)
    sim_neg_norm_enc = F.cosine_similarity(train_enc_neg, norm_enc.unsqueeze(0), dim=1)
    sim_neg_norm_dec = F.cosine_similarity(train_dec_neg, norm_dec.unsqueeze(0), dim=1)
    sim_all_norm_enc = F.cosine_similarity(train_enc, norm_enc.unsqueeze(0), dim=1)
    sim_all_norm_dec = F.cosine_similarity(train_dec, norm_dec.unsqueeze(0), dim=1)
    # 进行排序
    sort_sim_pos_norm_enc, indices = torch.sort(sim_pos_norm_enc)
    sort_sim_pos_norm_dec, indices = torch.sort(sim_pos_norm_dec)
    sort_sim_neg_norm_enc, indices = torch.sort(sim_neg_norm_enc)
    sort_sim_neg_norm_dec, indices = torch.sort(sim_neg_norm_dec)

    
    ## 初始化参数
    mean_pos_enc = torch.mean(sort_sim_pos_norm_enc).cpu().detach().numpy()
    std_pos_enc = torch.std(sort_sim_pos_norm_enc).cpu().detach().numpy()
    mean_pos_dec = torch.mean(sort_sim_pos_norm_dec).cpu().detach().numpy()
    std_pos_dec = torch.std(sort_sim_pos_norm_dec).cpu().detach().numpy()
    mean_neg_enc = torch.mean(sort_sim_neg_norm_enc).cpu().detach().numpy()
    std_neg_enc = torch.std(sort_sim_neg_norm_enc).cpu().detach().numpy()
    mean_neg_dec = torch.mean(sort_sim_neg_norm_dec).cpu().detach().numpy()
    std_neg_dec = torch.std(sort_sim_neg_norm_dec).cpu().detach().numpy()
    initial_params_enc = [mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc]
    initial_params_dec = [mean_pos_dec, std_pos_dec, mean_neg_dec, std_neg_dec]
    # 拟合高斯分布
    fit_enc = opt.minimize(log_likelihood, initial_params_enc, args=(sim_all_norm_enc,), method='Nelder-Mead')
    fit_dec = opt.minimize(log_likelihood, initial_params_dec, args=(sim_all_norm_dec,), method='Nelder-Mead') 
    # print("enc init")
    # print(initial_params_enc)
    # print("dec init")
    # print(initial_params_dec)
    mean1_enc, std1_enc, mean2_enc, std2_enc = fit_enc.x
    mean1_dec, std1_dec, mean2_dec, std2_dec = fit_dec.x
    # print("encoder:")
    # print(mean1_enc, std1_enc, mean2_enc, std2_enc)
    # print("decoder:")
    # print(mean1_dec, std1_dec, mean2_dec, std2_dec)
    # 选择均值小的作为正常样本的均值
    if mean1_enc < mean2_enc:
        mean_pos_enc, mean_neg_enc = mean1_enc, mean2_enc
        std_pos_enc, std_neg_enc = std1_enc, std2_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    else:
        mean_pos_enc, mean_neg_enc = mean2_enc, mean1_enc
        std_pos_enc, std_neg_enc = std2_enc, std1_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    if mean1_dec < mean2_dec:
        mean_pos_dec, mean_neg_dec = mean1_dec, mean2_dec
        std_pos_dec, std_neg_dec = std1_dec, std2_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    else:
        mean_pos_dec, mean_neg_dec = mean2_dec, mean1_dec
        std_pos_dec, std_neg_dec = std2_dec, std1_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    # gaussian_pos_enc = dist.Normal(mean1_enc, std1_enc)
    # gaussian_neg_enc = dist.Normal(mean2_enc, std2_enc)
    # gaussian_pos_dec = dist.Normal(mean1_dec, std1_dec)
    # gaussian_neg_dec = dist.Normal(mean2_dec, std2_dec)
    
    # 计算测试数据与正常样本的余弦相似度
    test_enc = F.cosine_similarity(F.normalize(model(x_test)[0], p=2, dim=1), norm_enc.unsqueeze(0), dim=1)
    test_dec = F.cosine_similarity(F.normalize(model(x_test)[1], p=2, dim=1), norm_dec.unsqueeze(0), dim=1)
    # 使用解码器和编码器分别预测
    y_pred_enc = torch.where(gaussian_pos_enc.log_prob(test_enc) > gaussian_neg_enc.log_prob(test_enc), 1, 0)
    y_pred_dec = torch.where(gaussian_pos_dec.log_prob(test_dec) > gaussian_neg_dec.log_prob(test_dec), 1, 0)
    # 投票预测
    diff_enc = torch.abs(gaussian_pos_enc.log_prob(test_enc)-gaussian_neg_enc.log_prob(test_enc))
    diff_dec = torch.abs(gaussian_pos_dec.log_prob(test_dec)-gaussian_neg_dec.log_prob(test_dec))
    y_pred = torch.where(diff_enc > diff_dec, y_pred_enc, y_pred_dec)
    return y_pred,y_pred_enc,y_pred_dec

初始训练模型  
用一小部分数据来训练模型  
训练的数据来自于 online_x_train

In [25]:
# 在线学习只使用20%的数据进行训练, 80%的数据用于在线学习和更新
online_x_train, online_x_test, online_y_train, online_y_test = train_test_split(x_train, y_train, test_size=0.8, random_state=42)
# 创建张量数据集
train_dataset = TensorDataset(online_x_train, online_y_train)
# 创建数据加载器
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
# 创建一个损失函数
criterion = CRCLoss(device, tem)
# 输入维度
input_dim = x_train.shape[1]
# 创建自编码器模型
model = AE(input_dim).to(device)
# 创建优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
# 调整模型进入训练模式
model.train()

AE(
  (encoder): Sequential(
    (0): Linear(in_features=121, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
  )
  (decoder): Sequential(
    (0): ReLU()
    (1): Linear(in_features=32, out_features=64, bias=True)
    (2): ReLU()
    (3): Linear(in_features=64, out_features=121, bias=True)
  )
)

## 训练模型

In [26]:
########################## 初始化训练模型 ##########################
for epoch in tqdm(range(epochs)):
    
    #  j是批次索引，data是一个元组，包含输入和标签
    for _ ,data in enumerate(train_loader,0):
        # 获取输入和标签
        inputs, labels = data # inputs.shape = (128, 206), labels.shape = (128,)
        # 将标签移动到设备上
        labels = labels.to(device)
        # 优化器梯度清零
        optimizer.zero_grad()
        # 前向传播
        enc_features, dec_features = model(inputs.to(device))     
        # 计算损失
        loss=criterion(enc_features, labels)+criterion(dec_features, labels)
        # 反向传播
        loss.backward()
        # 更新权重
        optimizer.step()
   


  0%|          | 0/1 [00:00<?, ?it/s]

In [27]:
#  将所有数据移动到设备上
# x_train = x_train.to(device)
# x_test = x_test.to(device)
online_x_train, online_y_train  = online_x_train.to(device), online_y_train.to(device)
# 克隆当前轮次的训练数据和测试数据
x_train_this_epoch, x_test_left_epoch, y_train_this_epoch, y_test_left_epoch = online_x_train.clone(), online_x_test.clone().to(device), online_y_train.clone(), online_y_test.clone()     

在线学习阶段

In [28]:
# 在线训练的过程，需要不断的测试新输入的数据，每次来一个新的数据，就需要测试一次，预测出标签，同时做一个累积，每当累积到一定数量的数据时，就需要微调模型
while len(x_test_left_epoch) > 0:
    # 如果剩余的数据少于采样间隔，则将所有剩余的数据作为这一轮的测试数据
    if len(x_test_left_epoch) < sample_interval:
        x_test_this_epoch = x_test_left_epoch.clone()
        x_test_left_epoch.resize_(0)
        y_test_this_epoch = y_test_left_epoch.clone()
        y_test_left_epoch.resize_(0)
        
    # 否则，从剩余的数据中采样一部分作为这一轮的测试数据
    else:
        x_test_this_epoch = x_test_left_epoch[:sample_interval].clone()
        x_test_left_epoch = x_test_left_epoch[sample_interval:]
        y_test_this_epoch = y_test_left_epoch[:sample_interval].clone()
        y_test_left_epoch = y_test_left_epoch[sample_interval:]
    
    # 据训练集里的正常样本的特征得出一个平均正常特征
    ## online_y_train == 0是正常样本的标签
    ## online_x_train[(online_y_train == 0)].shape   torch.Size([11190, 206]) 之所以要加squeeze()，是为了防止避免下面的情况[1,11190,206]
    ## 论文里有提到，即采用编码器的输出，也采用解码器的输出
    normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
    normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
    # 预测标签
    predict_label,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x_test_this_epoch,model)
    # 评估准确性
    evaluate(y_test_this_epoch, predict_label)
    
    # 随机翻转
    num_flips = int(flip_percent * len(predict_label))
    shuffle_index = np.random.choice(len(predict_label), num_flips, replace=False)
    # 翻转标签
    flip_label = predict_label.clone()
    flip_label[shuffle_index] = 1 - flip_label[shuffle_index]
    flip_label = flip_label.to(device)
    # 更新数据集
    x_train_this_epoch = torch.cat((x_train_this_epoch, x_test_this_epoch), 0)
    y_train_this_epoch = torch.cat((y_train_this_epoch, flip_label), 0)
    
    train_ds=TensorDataset(x_train_this_epoch, y_train_this_epoch)
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=True)
    
    for epoch in tqdm(range(epoch_online)):
        for _ ,data in enumerate(train_dl,0):
            inputs, labels = data
            labels = labels.to(device)
            optimizer.zero_grad()
            enc_features, dec_features = model(inputs.to(device))
            loss = criterion(enc_features, labels) + criterion(dec_features, labels)
            loss.backward()
            optimizer.step()
        

Confusion matrix
[[856 200]
 [ 27 917]]
Accuracy  0.8865
Precision  0.8209489704565801
Recall  0.9713983050847458
F1 score  0.8898592916060165


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[768 278]
 [ 14 940]]
Accuracy  0.854
Precision  0.7717569786535303
Recall  0.9853249475890985
F1 score  0.8655616942909761


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[789 281]
 [ 13 917]]
Accuracy  0.853
Precision  0.7654424040066778
Recall  0.986021505376344
F1 score  0.8618421052631579


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[812 296]
 [ 12 880]]
Accuracy  0.846
Precision  0.7482993197278912
Recall  0.9865470852017937
F1 score  0.851063829787234


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[787 286]
 [ 24 903]]
Accuracy  0.845
Precision  0.7594617325483599
Recall  0.9741100323624595
F1 score  0.8534971644612477


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[803 263]
 [ 15 919]]
Accuracy  0.861
Precision  0.7774957698815567
Recall  0.9839400428265525
F1 score  0.8686200378071833


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[747 325]
 [ 19 909]]
Accuracy  0.828
Precision  0.7366288492706645
Recall  0.9795258620689655
F1 score  0.8408880666049954


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[768 285]
 [  8 939]]
Accuracy  0.8535
Precision  0.7671568627450981
Recall  0.9915522703273495
F1 score  0.8650391524643022


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[740 330]
 [ 16 914]]
Accuracy  0.827
Precision  0.7347266881028939
Recall  0.9827956989247312
F1 score  0.8408463661453542


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[769 302]
 [ 18 911]]
Accuracy  0.84
Precision  0.7510305028854081
Recall  0.9806243272335845
F1 score  0.8506069094304388


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[757 303]
 [  9 931]]
Accuracy  0.844
Precision  0.7544570502431118
Recall  0.9904255319148936
F1 score  0.8564857405703772


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[624 426]
 [  9 941]]
Accuracy  0.7825
Precision  0.6883686905632772
Recall  0.9905263157894737
F1 score  0.8122572291756581


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[619 414]
 [  4 963]]
Accuracy  0.791
Precision  0.6993464052287581
Recall  0.9958634953464323
F1 score  0.8216723549488054


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[637 442]
 [  8 913]]
Accuracy  0.775
Precision  0.67380073800738
Recall  0.991313789359392
F1 score  0.8022847100175747


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[649 441]
 [ 12 898]]
Accuracy  0.7735
Precision  0.6706497386109037
Recall  0.9868131868131869
F1 score  0.7985771453979547


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[626 403]
 [  9 962]]
Accuracy  0.794
Precision  0.7047619047619048
Recall  0.9907312049433573
F1 score  0.8236301369863014


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[629 436]
 [ 14 921]]
Accuracy  0.775
Precision  0.6787030213706706
Recall  0.9850267379679144
F1 score  0.8036649214659686


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[611 453]
 [ 15 921]]
Accuracy  0.766
Precision  0.6703056768558951
Recall  0.9839743589743589
F1 score  0.7974025974025974


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[607 433]
 [ 11 949]]
Accuracy  0.778
Precision  0.6866859623733719
Recall  0.9885416666666667
F1 score  0.8104184457728437


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[617 493]
 [ 16 874]]
Accuracy  0.7455
Precision  0.6393562545720556
Recall  0.9820224719101124
F1 score  0.7744793974302171


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[676 460]
 [ 11 853]]
Accuracy  0.7645
Precision  0.6496572734196496
Recall  0.9872685185185185
F1 score  0.7836472209462563


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[636 418]
 [ 14 932]]
Accuracy  0.784
Precision  0.6903703703703704
Recall  0.985200845665962
F1 score  0.8118466898954704


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[614 405]
 [ 10 971]]
Accuracy  0.7925
Precision  0.7056686046511628
Recall  0.9898063200815495
F1 score  0.8239287229529062


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[624 411]
 [ 10 955]]
Accuracy  0.7895
Precision  0.6991215226939971
Recall  0.9896373056994818
F1 score  0.8193908193908194


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[626 429]
 [  7 938]]
Accuracy  0.782
Precision  0.6861741038771031
Recall  0.9925925925925926
F1 score  0.8114186851211073


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[643 440]
 [ 16 901]]
Accuracy  0.772
Precision  0.6718866517524236
Recall  0.9825517993456925
F1 score  0.7980513728963685


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[603 466]
 [ 13 918]]
Accuracy  0.7605
Precision  0.6632947976878613
Recall  0.9860365198711063
F1 score  0.7930885529157667


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[658 395]
 [  5 942]]
Accuracy  0.8
Precision  0.7045624532535527
Recall  0.9947201689545935
F1 score  0.8248686514886164


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[627 438]
 [ 12 923]]
Accuracy  0.775
Precision  0.6781778104335048
Recall  0.9871657754010695
F1 score  0.804006968641115


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[663 445]
 [ 10 882]]
Accuracy  0.7725
Precision  0.6646571213263
Recall  0.9887892376681614
F1 score  0.7949526813880127


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[664 426]
 [ 15 895]]
Accuracy  0.7795
Precision  0.6775170325510976
Recall  0.9835164835164835
F1 score  0.8023307933662035


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[638 439]
 [ 17 906]]
Accuracy  0.772
Precision  0.6736059479553903
Recall  0.9815817984832069
F1 score  0.798941798941799


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[619 437]
 [  9 935]]
Accuracy  0.777
Precision  0.6814868804664723
Recall  0.9904661016949152
F1 score  0.8074265975820379


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[667 428]
 [  8 897]]
Accuracy  0.782
Precision  0.6769811320754717
Recall  0.9911602209944751
F1 score  0.8044843049327354


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[638 432]
 [ 14 916]]
Accuracy  0.777
Precision  0.6795252225519288
Recall  0.9849462365591398
F1 score  0.8042142230026339


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[648 413]
 [ 12 927]]
Accuracy  0.7875
Precision  0.6917910447761194
Recall  0.987220447284345
F1 score  0.8135146994295743


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[670 443]
 [ 14 873]]
Accuracy  0.7715
Precision  0.6633738601823708
Recall  0.9842164599774521
F1 score  0.7925556059918293


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[683 421]
 [  9 887]]
Accuracy  0.785
Precision  0.6781345565749235
Recall  0.9899553571428571
F1 score  0.8049001814882033


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[617 424]
 [ 13 946]]
Accuracy  0.7815
Precision  0.6905109489051094
Recall  0.986444212721585
F1 score  0.8123658222413053


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[644 414]
 [  5 937]]
Accuracy  0.7905
Precision  0.6935603256846781
Recall  0.994692144373673
F1 score  0.8172699520279111


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[648 430]
 [  8 914]]
Accuracy  0.781
Precision  0.6800595238095238
Recall  0.9913232104121475
F1 score  0.8067078552515445


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[636 452]
 [  5 907]]
Accuracy  0.7715
Precision  0.6674025018395879
Recall  0.9945175438596491
F1 score  0.7987670629678556


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[654 436]
 [  8 902]]
Accuracy  0.778
Precision  0.6741405082212257
Recall  0.9912087912087912
F1 score  0.802491103202847


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[640 410]
 [ 13 937]]
Accuracy  0.7885
Precision  0.6956198960653304
Recall  0.9863157894736843
F1 score  0.8158467566390945


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[630 424]
 [ 12 934]]
Accuracy  0.782
Precision  0.6877761413843888
Recall  0.9873150105708245
F1 score  0.8107638888888888


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[632 409]
 [ 10 949]]
Accuracy  0.7905
Precision  0.698821796759941
Recall  0.9895724713242962
F1 score  0.8191627104013811


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[645 442]
 [  7 906]]
Accuracy  0.7755
Precision  0.672106824925816
Recall  0.9923329682365827
F1 score  0.8014153029632906


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[657 420]
 [  7 916]]
Accuracy  0.7865
Precision  0.6856287425149701
Recall  0.9924160346695557
F1 score  0.8109783089862771


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[632 418]
 [  9 941]]
Accuracy  0.7865
Precision  0.6924208977189109
Recall  0.9905263157894737
F1 score  0.8150714595062798


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[682 404]
 [  7 907]]
Accuracy  0.7945
Precision  0.6918382913806255
Recall  0.9923413566739606
F1 score  0.8152808988764045


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[230 181]
 [  5 363]]
Accuracy  0.7612323491655969
Precision  0.6672794117647058
Recall  0.9864130434782609
F1 score  0.7960526315789473


  0%|          | 0/1 [00:00<?, ?it/s]

# 评估模型（在测试集上训练）

In [29]:
normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
x_test = x_test.to(device)
y_pred,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch,y_train_this_epoch, x_test, model)
evaluate(y_test, y_pred)

Confusion matrix
[[ 7068  2643]
 [  290 12543]]
Accuracy  0.8698988644428672
Precision  0.8259581193204267
Recall  0.9774020104418296
F1 score  0.8953210321567507


# 零日攻击检测

In [30]:
df_train = pd.read_csv('en_KDDTrain+.csv')
df_test = pd.read_csv('en_KDDTest+.csv')
# 归一化
exclude_columns=['label','label2','class']
normalize_columns = [c for c in df_train.columns if c not in exclude_columns]

normalize = MinMaxScaler().fit(df_test[normalize_columns])
df_test[normalize_columns] = normalize.transform(df_test[normalize_columns])



attacks_train = set(df_train['label'].unique())
attacks_test = set(df_test['label'].unique())
# 仅仅在测试集中出现的攻击类别
attacks_only_test = attacks_test - attacks_train
indices_unseen = df_test[df_test['label'].isin(attacks_only_test)].index
# 在训练集和测试集中都出现的攻击类别
indices_seen = df_test[df_test['label'].isin(attacks_train&attacks_test)].index

In [31]:
df_seen = df_test.loc[indices_seen]
df_unseen = df_test.loc[indices_unseen]

In [32]:
seen_dos = df_seen[df_seen['class']=='DoS']
seen_probe = df_seen[df_seen['class']=='Probe']
seen_r2l = df_seen[df_seen['class']=='R2L']
seen_u2r = df_seen[df_seen['class']=='U2R']

In [33]:
unseen_dos = df_unseen[df_unseen['class']=='DoS']
unseen_probe = df_unseen[df_unseen['class']=='Probe']
unseen_r2l = df_unseen[df_unseen['class']=='R2L']
unseen_u2r = df_unseen[df_unseen['class']=='U2R']

In [34]:
def predict_df(df):
    x=torch.FloatTensor(df.drop(columns=['label','label2','class']).to_numpy()).to(device)
    y=torch.LongTensor(df['label2'].to_numpy()).to(device)
    y_pred,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x, model)
    # print(y_pred)
    evaluate(y, y_pred)

In [35]:
df_test['class'].unique()

array(['DoS', 'normal', 'Probe', 'R2L', 'U2R'], dtype=object)

In [36]:
predict_df(seen_dos)
predict_df(seen_probe)
predict_df(seen_r2l)
predict_df(seen_u2r)

Confusion matrix
[[   0    0]
 [ 288 5453]]
Accuracy  0.9498345236021599
Precision  1.0
Recall  0.9498345236021599
F1 score  0.974271931391817
Confusion matrix
[[1106]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0
Confusion matrix
[[2199]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0
Confusion matrix
[[37]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0


In [37]:
predict_df(unseen_dos)
predict_df(unseen_probe)
predict_df(unseen_r2l)
predict_df(unseen_u2r)

Confusion matrix
[[   0    0]
 [   2 1715]]
Accuracy  0.9988351776354106
Precision  1.0
Recall  0.9988351776354106
F1 score  0.9994172494172494
Confusion matrix
[[1315]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0
Confusion matrix
[[555]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0
Confusion matrix
[[163]]
Accuracy  1.0
Precision  1.0
Recall  1.0
F1 score  1.0
