# 加载模型

导入必要的库

In [1]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch import nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
from sklearn.base import BaseEstimator, TransformerMixin
import math
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
import scipy.optimize as opt
import torch.distributions as dist
from sklearn.metrics import accuracy_score
import argparse
import warnings
from tqdm.notebook import tqdm_notebook as tqdm
from collections import defaultdict

In [2]:
warnings.filterwarnings('ignore')

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

超参数设置

In [4]:
# 超参数
tem = 0.02
bs = 128
seed = 5009
epochs = 1
epoch_online=1
sample_interval = 2000
flip_percent = 0.2

## 加载数据集

In [5]:
def get_dataset():
    train_data=pd.read_csv('en_KDDTrain+.csv')
    test_data=pd.read_csv('en_KDDTest+.csv')
    y_train=train_data['label2']
    y_test=test_data['label2']
    X_train=train_data.drop(columns=['label2','class','label'])
    X_test=test_data.drop(columns=['label2','class','label'])
    normalize=MinMaxScaler()
    X_train=normalize.fit_transform(X_train)
    X_test=normalize.fit_transform(X_test)
    return X_train,y_train,X_test,y_test

In [6]:
x_train,y_train,x_test,y_test=get_dataset()
# 转换为torch张量
x_train,y_train=torch.FloatTensor(x_train).to(device),torch.LongTensor(y_train).to(device)
x_test,y_test=torch.FloatTensor(x_test).to(device),torch.LongTensor(y_test).to(device)

In [7]:
def evaluate(y,y_pred):
    y= y.cpu().detach().numpy()
    y_pred= y_pred.cpu().detach().numpy()
    # 混淆矩阵
    print("Confusion matrix")
    print(confusion_matrix(y, y_pred))
    # Accuracy 
    print('Accuracy ',accuracy_score(y, y_pred))
    # Precision 
    print('Precision ',precision_score(y, y_pred))
    # Recall
    print('Recall ',recall_score(y, y_pred))
    # F1 score
    print('F1 score ',f1_score(y,y_pred))

In [8]:
import matplotlib.pyplot as plt
def plot_loss(losses,epoch):
    plt.figure(figsize=(10,5))
    plt.title(f"{epoch} Training Loss")
    plt.plot(losses, marker='o')
    plt.xlabel("Iterations")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

## 加载模型

AE自编码器模块

In [9]:
class AE(nn.Module):
    def __init__(self, input_dim):
        super(AE, self).__init__()
        # 计算输入维度的最近的2的幂次方，比如输入维度是206，则最近的2的幂次方是128
        nearest_power_of_2 = 2 ** round(math.log2(input_dim))
        
        second_fourth_layer_size = nearest_power_of_2 // 2
        third_layer_size = nearest_power_of_2 // 4
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, third_layer_size)
        )
        self.decoder = nn.Sequential(
            nn.ReLU(),
            nn.Linear(third_layer_size, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, input_dim)
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

InfoNCE对比损失模块

In [10]:
class InfoNCE(nn.Module):
    def __init__(self, device, temperature=0.1, scale_by_temperature=True):
        super(InfoNCE, self).__init__()
        self.device = device
        self.temperature = temperature
        self.scale_by_temperature = scale_by_temperature

    def forward(self, features, labels=None):
        # 计算特征的归一化表示
        features = F.normalize(features, p=2, dim=1)
        batch_size = features.shape[0]
        num_norm = len(labels==0)
        ## contiguous方法确保张量在内存是连续存储的，因为变换视图操作需要确保张量在内存中是连续存储的
        labels = labels.contiguous().view(-1, 1) # batch_size * 1
        
        if labels.shape[0] != batch_size:
            raise ValueError('Batch size of features and labels do not match.')
        
        # 计算余弦相似度，cosine_sim[i][j]表示features[i]和features[j]的余弦相似度，矩阵大小为batch_size * batch_size
        cosine_sim = torch.nn.functional.cosine_similarity(features.unsqueeze(1), features.unsqueeze(0), dim = -1)/self.temperature
        # 将余弦相似度的对角线元素设置为0
        mask_diag = torch.eye(batch_size, dtype=torch.bool)
        cosine_sim[mask_diag] = 0
        # 正样本对
        sim_pos = cosine_sim[(labels==0).squeeze()]
        # 正样本对间的余弦相似度
        sim_pos_pos = sim_pos[:,(labels==0).squeeze()] 
        # 正样本与负样本间的余弦相似度
        sim_pos_neg = sim_pos[:,(labels==1).squeeze()]
        # 计算正样本与负样本间的分数和
        sum_pos_neg = torch.sum(torch.exp(sim_pos_neg), axis=1, keepdims=True)
        # 计算分母
        denominator = torch.exp(sim_pos_pos) + sum_pos_neg       
        loss = -(sim_pos_pos-torch.log(denominator))  
        
        
        if self.scale_by_temperature:
            loss = loss * self.temperature
        # 计算损失
        loss= loss.mean()
        return loss

## ADM自主决策

In [11]:
def gaussian_pdf(x, mean, std):
    pdf = 1/(std*np.sqrt(2*np.pi))*np.exp(-(x-mean)**2/(2*std**2))
    return pdf
def log_likelihood(params,data):
    data = data.cpu().detach().numpy()
    mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc = params
    pdf1 = gaussian_pdf(data, mean_pos_enc, std_pos_enc)
    pdf2 = gaussian_pdf(data, mean_neg_enc, std_neg_enc)
    mixture_pdf = 0.5*pdf1 + 0.5*pdf2
    log_likelihood = -np.sum(np.log(mixture_pdf))
    
    return log_likelihood
def predict(norm_enc, norm_dec, x_train, y_train, x_test, model):
    x_train_pos=x_train[(y_train==0).squeeze()]
    x_train_neg=x_train[(y_train==1).squeeze()]
    
    # 训练集全体样本编码和解码特征
    train_enc = F.normalize(model(x_train)[0], p=2, dim=1)
    train_dec = F.normalize(model(x_train)[1], p=2, dim=1)
    # 训练集正样本编码和解码特征
    train_enc_pos = F.normalize(model(x_train_pos)[0], p=2, dim=1)
    train_dec_pos = F.normalize(model(x_train_pos)[1], p=2, dim=1)
    # 训练集负样本编码和解码特征
    train_enc_neg = F.normalize(model(x_train_neg)[0], p=2, dim=1)
    train_dec_neg = F.normalize(model(x_train_neg)[1], p=2, dim=1)
    
    # 分别计算训练集正样本特征和平均正样本特征的余弦相似度 负样本同理 全体样本同理 
    sim_pos_norm_enc = F.cosine_similarity(train_enc_pos, norm_enc.unsqueeze(0), dim=1) 
    sim_pos_norm_dec = F.cosine_similarity(train_dec_pos, norm_dec.unsqueeze(0), dim=1)
    sim_neg_norm_enc = F.cosine_similarity(train_enc_neg, norm_enc.unsqueeze(0), dim=1)
    sim_neg_norm_dec = F.cosine_similarity(train_dec_neg, norm_dec.unsqueeze(0), dim=1)
    sim_all_norm_enc = F.cosine_similarity(train_enc, norm_enc.unsqueeze(0), dim=1)
    sim_all_norm_dec = F.cosine_similarity(train_dec, norm_dec.unsqueeze(0), dim=1)
    # 进行排序
    sort_sim_pos_norm_enc, indices = torch.sort(sim_pos_norm_enc)
    sort_sim_pos_norm_dec, indices = torch.sort(sim_pos_norm_dec)
    sort_sim_neg_norm_enc, indices = torch.sort(sim_neg_norm_enc)
    sort_sim_neg_norm_dec, indices = torch.sort(sim_neg_norm_dec)

    
    ## 初始化参数
    mean_pos_enc = torch.mean(sort_sim_pos_norm_enc).cpu().detach().numpy()
    std_pos_enc = torch.std(sort_sim_pos_norm_enc).cpu().detach().numpy()
    mean_pos_dec = torch.mean(sort_sim_pos_norm_dec).cpu().detach().numpy()
    std_pos_dec = torch.std(sort_sim_pos_norm_dec).cpu().detach().numpy()
    mean_neg_enc = torch.mean(sort_sim_neg_norm_enc).cpu().detach().numpy()
    std_neg_enc = torch.std(sort_sim_neg_norm_enc).cpu().detach().numpy()
    mean_neg_dec = torch.mean(sort_sim_neg_norm_dec).cpu().detach().numpy()
    std_neg_dec = torch.std(sort_sim_neg_norm_dec).cpu().detach().numpy()
    initial_params_enc = [mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc]
    initial_params_dec = [mean_pos_dec, std_pos_dec, mean_neg_dec, std_neg_dec]
    # 拟合高斯分布
    fit_enc = opt.minimize(log_likelihood, initial_params_enc, args=(sim_all_norm_enc,), method='Nelder-Mead')
    fit_dec = opt.minimize(log_likelihood, initial_params_dec, args=(sim_all_norm_dec,), method='Nelder-Mead') 
    # print("enc init")
    # print(initial_params_enc)
    # print("dec init")
    # print(initial_params_dec)
    mean1_enc, std1_enc, mean2_enc, std2_enc = fit_enc.x
    mean1_dec, std1_dec, mean2_dec, std2_dec = fit_dec.x
    # print("encoder:")
    # print(mean1_enc, std1_enc, mean2_enc, std2_enc)
    # print("decoder:")
    # print(mean1_dec, std1_dec, mean2_dec, std2_dec)
    # 选择均值小的作为正常样本的均值
    if mean1_enc < mean2_enc:
        mean_pos_enc, mean_neg_enc = mean1_enc, mean2_enc
        std_pos_enc, std_neg_enc = std1_enc, std2_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    else:
        mean_pos_enc, mean_neg_enc = mean2_enc, mean1_enc
        std_pos_enc, std_neg_enc = std2_enc, std1_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    if mean1_dec < mean2_dec:
        mean_pos_dec, mean_neg_dec = mean1_dec, mean2_dec
        std_pos_dec, std_neg_dec = std1_dec, std2_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    else:
        mean_pos_dec, mean_neg_dec = mean2_dec, mean1_dec
        std_pos_dec, std_neg_dec = std2_dec, std1_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    # gaussian_pos_enc = dist.Normal(mean1_enc, std1_enc)
    # gaussian_neg_enc = dist.Normal(mean2_enc, std2_enc)
    # gaussian_pos_dec = dist.Normal(mean1_dec, std1_dec)
    # gaussian_neg_dec = dist.Normal(mean2_dec, std2_dec)
    
    # 计算测试数据与正常样本的余弦相似度
    test_enc = F.cosine_similarity(F.normalize(model(x_test)[0], p=2, dim=1), norm_enc.unsqueeze(0), dim=1)
    test_dec = F.cosine_similarity(F.normalize(model(x_test)[1], p=2, dim=1), norm_dec.unsqueeze(0), dim=1)
    # 使用解码器和编码器分别预测
    y_pred_enc = torch.where(gaussian_pos_enc.log_prob(test_enc) > gaussian_neg_enc.log_prob(test_enc), 1, 0)
    y_pred_dec = torch.where(gaussian_pos_dec.log_prob(test_dec) > gaussian_neg_dec.log_prob(test_dec), 1, 0)
    # 投票预测
    diff_enc = torch.abs(gaussian_pos_enc.log_prob(test_enc)-gaussian_neg_enc.log_prob(test_enc))
    diff_dec = torch.abs(gaussian_pos_dec.log_prob(test_dec)-gaussian_neg_dec.log_prob(test_dec))
    y_pred = torch.where(diff_enc > diff_dec, y_pred_enc, y_pred_dec)
    return y_pred,y_pred_enc,y_pred_dec

初始训练模型  
用一小部分数据来训练模型  
训练的数据来自于 online_x_train

In [12]:
# 在线学习只使用20%的数据进行训练, 80%的数据用于在线学习和更新
online_x_train, online_x_test, online_y_train, online_y_test = train_test_split(x_train, y_train, test_size=0.8, random_state=42)
# 创建张量数据集
train_dataset = TensorDataset(online_x_train, online_y_train)
# 创建数据加载器
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
# 创建一个损失函数
criterion = InfoNCE(device, tem)
# 输入维度
input_dim = x_train.shape[1]
# 创建自编码器模型
model = AE(input_dim).to(device)
# 创建优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# 调整模型进入训练模式
model.train()

AE(
  (encoder): Sequential(
    (0): Linear(in_features=121, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
  )
  (decoder): Sequential(
    (0): ReLU()
    (1): Linear(in_features=32, out_features=64, bias=True)
    (2): ReLU()
    (3): Linear(in_features=64, out_features=121, bias=True)
  )
)

## 训练模型

In [13]:
########################## 初始化训练模型 ##########################
for epoch in tqdm(range(epochs)):
    
    #  j是批次索引，data是一个元组，包含输入和标签
    for _ ,data in enumerate(train_loader,0):
        # 获取输入和标签
        inputs, labels = data # inputs.shape = (128, 206), labels.shape = (128,)
        # 将标签移动到设备上
        labels = labels.to(device)
        # 优化器梯度清零
        optimizer.zero_grad()
        # 前向传播
        enc_features, dec_features = model(inputs.to(device))     
        # 计算损失
        loss=criterion(enc_features, labels)+criterion(dec_features, labels)
        # 反向传播
        loss.backward()
        # 更新权重
        optimizer.step()
   


  0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
#  将所有数据移动到设备上
# x_train = x_train.to(device)
# x_test = x_test.to(device)
online_x_train, online_y_train  = online_x_train.to(device), online_y_train.to(device)
# 克隆当前轮次的训练数据和测试数据
x_train_this_epoch, x_test_left_epoch, y_train_this_epoch, y_test_left_epoch = online_x_train.clone(), online_x_test.clone().to(device), online_y_train.clone(), online_y_test.clone()     

在线学习阶段

In [15]:
# 在线训练的过程，需要不断的测试新输入的数据，每次来一个新的数据，就需要测试一次，预测出标签，同时做一个累积，每当累积到一定数量的数据时，就需要微调模型
while len(x_test_left_epoch) > 0:
    # 如果剩余的数据少于采样间隔，则将所有剩余的数据作为这一轮的测试数据
    if len(x_test_left_epoch) < sample_interval:
        x_test_this_epoch = x_test_left_epoch.clone()
        x_test_left_epoch.resize_(0)
        y_test_this_epoch = y_test_left_epoch.clone()
        y_test_left_epoch.resize_(0)
        
    # 否则，从剩余的数据中采样一部分作为这一轮的测试数据
    else:
        x_test_this_epoch = x_test_left_epoch[:sample_interval].clone()
        x_test_left_epoch = x_test_left_epoch[sample_interval:]
        y_test_this_epoch = y_test_left_epoch[:sample_interval].clone()
        y_test_left_epoch = y_test_left_epoch[sample_interval:]
    
    # 据训练集里的正常样本的特征得出一个平均正常特征
    ## online_y_train == 0是正常样本的标签
    ## online_x_train[(online_y_train == 0)].shape   torch.Size([11190, 206]) 之所以要加squeeze()，是为了防止避免下面的情况[1,11190,206]
    ## 论文里有提到，即采用编码器的输出，也采用解码器的输出
    normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
    normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
    # 预测标签
    predict_label,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x_test_this_epoch, model)
    # 评估准确性
    evaluate(y_test_this_epoch, predict_label)
    
    # 随机翻转
    num_flips = int(flip_percent * len(predict_label))
    shuffle_index = np.random.choice(len(predict_label), num_flips, replace=False)
    # 翻转标签
    flip_label = predict_label.clone()
    flip_label[shuffle_index] = 1 - flip_label[shuffle_index]
    flip_label = flip_label.to(device)
    # 更新数据集
    x_train_this_epoch = torch.cat((x_train_this_epoch, x_test_this_epoch), 0)
    y_train_this_epoch = torch.cat((y_train_this_epoch, flip_label), 0)
    
    train_ds=TensorDataset(x_train_this_epoch, y_train_this_epoch)
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=True)
    
    for epoch in tqdm(range(epoch_online)):
        for _ ,data in enumerate(train_dl,0):
            inputs, labels = data
            labels = labels.to(device)
            optimizer.zero_grad()
            enc_features, dec_features = model(inputs.to(device))
            loss = criterion(enc_features, labels) + criterion(dec_features, labels)
            loss.backward()
            optimizer.step()
        

Confusion matrix
[[769 287]
 [ 23 921]]
Accuracy  0.845
Precision  0.7624172185430463
Recall  0.975635593220339
F1 score  0.8559479553903345


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[900 146]
 [ 32 922]]
Accuracy  0.911
Precision  0.8632958801498127
Recall  0.9664570230607966
F1 score  0.9119683481701286


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[952 118]
 [ 30 900]]
Accuracy  0.926
Precision  0.8840864440078585
Recall  0.967741935483871
F1 score  0.9240246406570842


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[1002  106]
 [  32  860]]
Accuracy  0.931
Precision  0.8902691511387164
Recall  0.9641255605381166
F1 score  0.9257265877287406


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[968 105]
 [ 38 889]]
Accuracy  0.9285
Precision  0.8943661971830986
Recall  0.9590075512405609
F1 score  0.9255596043727226


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[963 103]
 [ 30 904]]
Accuracy  0.9335
Precision  0.8977159880834161
Recall  0.9678800856531049
F1 score  0.9314786192684184


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[943 129]
 [ 32 896]]
Accuracy  0.9195
Precision  0.8741463414634146
Recall  0.9655172413793104
F1 score  0.9175627240143369


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[944 109]
 [ 19 928]]
Accuracy  0.936
Precision  0.8948891031822566
Recall  0.9799366420274551
F1 score  0.9354838709677419


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[966 104]
 [ 30 900]]
Accuracy  0.933
Precision  0.896414342629482
Recall  0.967741935483871
F1 score  0.9307135470527405


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[958 113]
 [ 30 899]]
Accuracy  0.9285
Precision  0.8883399209486166
Recall  0.9677072120559742
F1 score  0.9263266357547656


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[954 106]
 [ 21 919]]
Accuracy  0.9365
Precision  0.8965853658536586
Recall  0.9776595744680852
F1 score  0.9353689567430026


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[940 110]
 [ 20 930]]
Accuracy  0.935
Precision  0.8942307692307693
Recall  0.9789473684210527
F1 score  0.9346733668341709


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[916 117]
 [ 12 955]]
Accuracy  0.9355
Precision  0.8908582089552238
Recall  0.9875904860392968
F1 score  0.9367336929867582


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[923 156]
 [ 19 902]]
Accuracy  0.9125
Precision  0.8525519848771267
Recall  0.9793702497285559
F1 score  0.9115715007579586


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[955 135]
 [ 23 887]]
Accuracy  0.921
Precision  0.8679060665362035
Recall  0.9747252747252747
F1 score  0.9182194616977226


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[889 140]
 [ 20 951]]
Accuracy  0.92
Precision  0.8716773602199817
Recall  0.9794026776519053
F1 score  0.9224054316197866


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[917 148]
 [ 25 910]]
Accuracy  0.9135
Precision  0.8601134215500945
Recall  0.9732620320855615
F1 score  0.9131961866532865


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[908 156]
 [ 26 910]]
Accuracy  0.909
Precision  0.8536585365853658
Recall  0.9722222222222222
F1 score  0.9090909090909091


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[896 144]
 [ 21 939]]
Accuracy  0.9175
Precision  0.8670360110803325
Recall  0.978125
F1 score  0.9192364170337739


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[924 186]
 [ 29 861]]
Accuracy  0.8925
Precision  0.8223495702005731
Recall  0.9674157303370786
F1 score  0.8890036138358286


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[960 176]
 [ 20 844]]
Accuracy  0.902
Precision  0.8274509803921568
Recall  0.9768518518518519
F1 score  0.8959660297239915


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[890 164]
 [ 31 915]]
Accuracy  0.9025
Precision  0.8480074142724745
Recall  0.96723044397463
F1 score  0.9037037037037037


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[879 140]
 [ 20 961]]
Accuracy  0.92
Precision  0.8728428701180745
Recall  0.9796126401630989
F1 score  0.9231508165225745


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[882 153]
 [ 30 935]]
Accuracy  0.9085
Precision  0.859375
Recall  0.9689119170984456
F1 score  0.910862152946907


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[876 179]
 [ 17 928]]
Accuracy  0.902
Precision  0.8383017163504969
Recall  0.982010582010582
F1 score  0.9044834307992202


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[911 172]
 [ 31 886]]
Accuracy  0.8985
Precision  0.8374291115311909
Recall  0.9661941112322792
F1 score  0.8972151898734178


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[868 201]
 [ 24 907]]
Accuracy  0.8875
Precision  0.8185920577617328
Recall  0.9742212674543501
F1 score  0.889651790093183


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[893 160]
 [ 13 934]]
Accuracy  0.9135
Precision  0.8537477148080439
Recall  0.986272439281943
F1 score  0.9152376286134248


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[899 166]
 [ 18 917]]
Accuracy  0.908
Precision  0.8467220683287165
Recall  0.9807486631016042
F1 score  0.908820614469772


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[935 173]
 [ 25 867]]
Accuracy  0.901
Precision  0.8336538461538462
Recall  0.9719730941704036
F1 score  0.8975155279503105


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[908 182]
 [ 20 890]]
Accuracy  0.899
Precision  0.8302238805970149
Recall  0.978021978021978
F1 score  0.8980827447023209


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[860 217]
 [ 30 893]]
Accuracy  0.8765
Precision  0.8045045045045045
Recall  0.9674972914409534
F1 score  0.8785046728971962


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[839 217]
 [ 16 928]]
Accuracy  0.8835
Precision  0.8104803493449781
Recall  0.9830508474576272
F1 score  0.8884633796074677


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[858 237]
 [ 13 892]]
Accuracy  0.875
Precision  0.7900797165633304
Recall  0.9856353591160221
F1 score  0.8770894788593904


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[804 266]
 [ 19 911]]
Accuracy  0.8575
Precision  0.7740016992353441
Recall  0.9795698924731183
F1 score  0.8647365923113431


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[767 294]
 [ 16 923]]
Accuracy  0.845
Precision  0.7584223500410846
Recall  0.9829605963791267
F1 score  0.8562152133580705


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[783 330]
 [ 18 869]]
Accuracy  0.826
Precision  0.7247706422018348
Recall  0.979706877113867
F1 score  0.8331735378715245


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[770 334]
 [ 16 880]]
Accuracy  0.825
Precision  0.7248764415156508
Recall  0.9821428571428571
F1 score  0.8341232227488151


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[708 333]
 [ 17 942]]
Accuracy  0.825
Precision  0.7388235294117647
Recall  0.9822732012513035
F1 score  0.8433303491495077


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[718 340]
 [ 14 928]]
Accuracy  0.823
Precision  0.7318611987381703
Recall  0.9851380042462845
F1 score  0.8398190045248869


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[736 342]
 [  8 914]]
Accuracy  0.825
Precision  0.7277070063694268
Recall  0.9913232104121475
F1 score  0.8393021120293848


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[725 363]
 [ 11 901]]
Accuracy  0.813
Precision  0.7128164556962026
Recall  0.9879385964912281
F1 score  0.828125


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[747 343]
 [ 11 899]]
Accuracy  0.823
Precision  0.7238325281803543
Recall  0.987912087912088
F1 score  0.8355018587360595


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[726 324]
 [ 19 931]]
Accuracy  0.8285
Precision  0.7418326693227092
Recall  0.98
F1 score  0.8444444444444444


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[750 304]
 [ 15 931]]
Accuracy  0.8405
Precision  0.7538461538461538
Recall  0.9841437632135307
F1 score  0.8537368179734067


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[729 312]
 [ 14 945]]
Accuracy  0.837
Precision  0.7517899761336515
Recall  0.9854014598540146
F1 score  0.8528880866425993


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[755 332]
 [ 12 901]]
Accuracy  0.828
Precision  0.7307380373073804
Recall  0.9868565169769989
F1 score  0.8397017707362535


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[764 313]
 [ 11 912]]
Accuracy  0.838
Precision  0.7444897959183674
Recall  0.9880823401950163
F1 score  0.8491620111731844


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[726 324]
 [ 13 937]]
Accuracy  0.8315
Precision  0.7430610626486915
Recall  0.9863157894736843
F1 score  0.8475802804161013


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[770 316]
 [  9 905]]
Accuracy  0.8375
Precision  0.7411957411957412
Recall  0.9901531728665208
F1 score  0.8477751756440282


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[277 134]
 [  6 362]]
Accuracy  0.8202824133504493
Precision  0.7298387096774194
Recall  0.9836956521739131
F1 score  0.8379629629629629


  0%|          | 0/1 [00:00<?, ?it/s]

# 评估模型（在测试集上训练）

In [16]:
normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
x_test = x_test.to(device)
y_pred,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch,y_train_this_epoch , x_test , model)
evaluate(y_test, y_pred)

Confusion matrix
[[ 7568  2143]
 [  502 12331]]
Accuracy  0.8826738821859474
Precision  0.8519414121873704
Recall  0.9608821008337879
F1 score  0.9031383894239572
