# 加载模型

导入必要的库

In [1]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch import nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
from sklearn.base import BaseEstimator, TransformerMixin
import math
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
import scipy.optimize as opt
import torch.distributions as dist
from sklearn.metrics import accuracy_score
import argparse
import warnings
from tqdm.notebook import tqdm_notebook as tqdm
from collections import defaultdict

In [2]:
warnings.filterwarnings('ignore')

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

超参数设置

In [4]:
# 超参数
tem = 0.02
bs = 128
seed = 5009
seed_round = 5
epochs = 300
epoch_online=3
sample_interval = 2784
flip_percent = 0.05

## 加载数据集

In [5]:
def get_dataset():
    train_data=pd.read_csv('en_UNSW_NB15_train.csv')
    test_data=pd.read_csv('en_UNSW_NB15_test.csv')
    y_train=train_data['label']
    y_test=test_data['label']
    X_train=train_data.drop(columns=['label'])
    X_test=test_data.drop(columns=['label'])
    normalize=MinMaxScaler()
    X_train=normalize.fit_transform(X_train)
    X_test=normalize.fit_transform(X_test)
    return X_train,y_train,X_test,y_test

In [6]:
x_train,y_train,x_test,y_test=get_dataset()
# 转换为torch张量
x_train,y_train=torch.FloatTensor(x_train).to(device),torch.LongTensor(y_train).to(device)
x_test,y_test=torch.FloatTensor(x_test).to(device),torch.LongTensor(y_test).to(device)

In [7]:
def evaluate(y,y_pred):
    y= y.cpu().detach().numpy()
    y_pred= y_pred.cpu().detach().numpy()
    # 混淆矩阵
    print("Confusion matrix")
    print(confusion_matrix(y, y_pred))
    # Accuracy 
    print('Accuracy ',accuracy_score(y, y_pred))
    # Precision 
    print('Precision ',precision_score(y, y_pred))
    # Recall
    print('Recall ',recall_score(y, y_pred))
    # F1 score
    print('F1 score ',f1_score(y,y_pred))

In [8]:
import matplotlib.pyplot as plt
def plot_loss(losses,epoch):
    plt.figure(figsize=(10,5))
    plt.title(f"{epoch} Training Loss")
    plt.plot(losses, marker='o')
    plt.xlabel("Iterations")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

## 加载模型

AE自编码器模块

In [9]:
class AE(nn.Module):
    def __init__(self, input_dim):
        super(AE, self).__init__()
        # 计算输入维度的最近的2的幂次方，比如输入维度是206，则最近的2的幂次方是128
        nearest_power_of_2 = 2 ** round(math.log2(input_dim))
        
        second_fourth_layer_size = nearest_power_of_2 // 2
        third_layer_size = nearest_power_of_2 // 4
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, third_layer_size)
        )
        self.decoder = nn.Sequential(
            nn.ReLU(),
            nn.Linear(third_layer_size, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, input_dim)
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

CRC对比损失模块

In [10]:
class CRCLoss(nn.Module):
    def __init__(self, device, temperature=0.1, scale_by_temperature=True):
        super(CRCLoss, self).__init__()
        self.device = device
        self.temperature = temperature
        self.scale_by_temperature = scale_by_temperature

    def forward(self, features, labels=None):
        # 计算特征的归一化表示
        features = F.normalize(features, p=2, dim=1)
        batch_size = features.shape[0]
        num_norm = len(labels==0)
        ## contiguous方法确保张量在内存是连续存储的，因为变换视图操作需要确保张量在内存中是连续存储的
        labels = labels.contiguous().view(-1, 1) # batch_size * 1
        
        if labels.shape[0] != batch_size:
            raise ValueError('Batch size of features and labels do not match.')
        
        # 计算余弦相似度，cosine_sim[i][j]表示features[i]和features[j]的余弦相似度，矩阵大小为batch_size * batch_size
        cosine_sim = torch.nn.functional.cosine_similarity(features.unsqueeze(1), features.unsqueeze(0), dim = -1)/self.temperature
        # 将余弦相似度的对角线元素设置为0
        mask_diag = torch.eye(batch_size, dtype=torch.bool)
        cosine_sim[mask_diag] = 0
        # 正样本对
        sim_pos = cosine_sim[(labels==0).squeeze()]
        # 正样本对间的余弦相似度
        sim_pos_pos = sim_pos[:,(labels==0).squeeze()] 
        # 正样本与负样本间的余弦相似度
        sim_pos_neg = sim_pos[:,(labels==1).squeeze()]
        # 计算正样本与负样本间的分数和
        sum_pos_neg = torch.sum(torch.exp(sim_pos_neg))
        # 计算分母
        denominator = torch.exp(sim_pos_pos) + sum_pos_neg       
        loss = -(sim_pos_pos-torch.log(denominator))  
        
        
        if self.scale_by_temperature:
            loss = loss * self.temperature
        # 计算损失
        loss= loss.mean()
        return loss

## ADM自主决策

In [11]:
def gaussian_pdf(x, mean, std):
    pdf = 1/(std*np.sqrt(2*np.pi))*np.exp(-(x-mean)**2/(2*std**2))
    return pdf
def log_likelihood(params,data):
    data = data.cpu().detach().numpy()
    mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc = params
    pdf1 = gaussian_pdf(data, mean_pos_enc, std_pos_enc)
    pdf2 = gaussian_pdf(data, mean_neg_enc, std_neg_enc)
    mixture_pdf = 0.5*pdf1 + 0.5*pdf2
    log_likelihood = -np.sum(np.log(mixture_pdf))
    
    return log_likelihood
def predict(norm_enc, norm_dec, x_train, y_train, x_test, model):
    x_train_pos=x_train[(y_train==0).squeeze()]
    x_train_neg=x_train[(y_train==1).squeeze()]
    
    # 训练集全体样本编码和解码特征
    train_enc = F.normalize(model(x_train)[0], p=2, dim=1)
    train_dec = F.normalize(model(x_train)[1], p=2, dim=1)
    # 训练集正样本编码和解码特征
    train_enc_pos = F.normalize(model(x_train_pos)[0], p=2, dim=1)
    train_dec_pos = F.normalize(model(x_train_pos)[1], p=2, dim=1)
    # 训练集负样本编码和解码特征
    train_enc_neg = F.normalize(model(x_train_neg)[0], p=2, dim=1)
    train_dec_neg = F.normalize(model(x_train_neg)[1], p=2, dim=1)
    
    # 分别计算训练集正样本特征和平均正样本特征的余弦相似度 负样本同理 全体样本同理 
    sim_pos_norm_enc = F.cosine_similarity(train_enc_pos, norm_enc.unsqueeze(0), dim=1) 
    sim_pos_norm_dec = F.cosine_similarity(train_dec_pos, norm_dec.unsqueeze(0), dim=1)
    sim_neg_norm_enc = F.cosine_similarity(train_enc_neg, norm_enc.unsqueeze(0), dim=1)
    sim_neg_norm_dec = F.cosine_similarity(train_dec_neg, norm_dec.unsqueeze(0), dim=1)
    sim_all_norm_enc = F.cosine_similarity(train_enc, norm_enc.unsqueeze(0), dim=1)
    sim_all_norm_dec = F.cosine_similarity(train_dec, norm_dec.unsqueeze(0), dim=1)
    # 进行排序
    sort_sim_pos_norm_enc, indices = torch.sort(sim_pos_norm_enc)
    sort_sim_pos_norm_dec, indices = torch.sort(sim_pos_norm_dec)
    sort_sim_neg_norm_enc, indices = torch.sort(sim_neg_norm_enc)
    sort_sim_neg_norm_dec, indices = torch.sort(sim_neg_norm_dec)

    
    ## 初始化参数
    mean_pos_enc = torch.mean(sort_sim_pos_norm_enc).cpu().detach().numpy()
    std_pos_enc = torch.std(sort_sim_pos_norm_enc).cpu().detach().numpy()
    mean_pos_dec = torch.mean(sort_sim_pos_norm_dec).cpu().detach().numpy()
    std_pos_dec = torch.std(sort_sim_pos_norm_dec).cpu().detach().numpy()
    mean_neg_enc = torch.mean(sort_sim_neg_norm_enc).cpu().detach().numpy()
    std_neg_enc = torch.std(sort_sim_neg_norm_enc).cpu().detach().numpy()
    mean_neg_dec = torch.mean(sort_sim_neg_norm_dec).cpu().detach().numpy()
    std_neg_dec = torch.std(sort_sim_neg_norm_dec).cpu().detach().numpy()
    initial_params_enc = [mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc]
    initial_params_dec = [mean_pos_dec, std_pos_dec, mean_neg_dec, std_neg_dec]
    # 拟合高斯分布
    fit_enc = opt.minimize(log_likelihood, initial_params_enc, args=(sim_all_norm_enc,), method='Nelder-Mead')
    fit_dec = opt.minimize(log_likelihood, initial_params_dec, args=(sim_all_norm_dec,), method='Nelder-Mead') 
    # print("enc init")
    # print(initial_params_enc)
    # print("dec init")
    # print(initial_params_dec)
    mean1_enc, std1_enc, mean2_enc, std2_enc = fit_enc.x
    mean1_dec, std1_dec, mean2_dec, std2_dec = fit_dec.x
    # print("encoder:")
    # print(mean1_enc, std1_enc, mean2_enc, std2_enc)
    # print("decoder:")
    # print(mean1_dec, std1_dec, mean2_dec, std2_dec)
    # 选择均值小的作为正常样本的均值
    if mean1_enc < mean2_enc:
        mean_pos_enc, mean_neg_enc = mean1_enc, mean2_enc
        std_pos_enc, std_neg_enc = std1_enc, std2_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    else:
        mean_pos_enc, mean_neg_enc = mean2_enc, mean1_enc
        std_pos_enc, std_neg_enc = std2_enc, std1_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    if mean1_dec < mean2_dec:
        mean_pos_dec, mean_neg_dec = mean1_dec, mean2_dec
        std_pos_dec, std_neg_dec = std1_dec, std2_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    else:
        mean_pos_dec, mean_neg_dec = mean2_dec, mean1_dec
        std_pos_dec, std_neg_dec = std2_dec, std1_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    # gaussian_pos_enc = dist.Normal(mean1_enc, std1_enc)
    # gaussian_neg_enc = dist.Normal(mean2_enc, std2_enc)
    # gaussian_pos_dec = dist.Normal(mean1_dec, std1_dec)
    # gaussian_neg_dec = dist.Normal(mean2_dec, std2_dec)
    
    # 计算测试数据与正常样本的余弦相似度
    test_enc = F.cosine_similarity(F.normalize(model(x_test)[0], p=2, dim=1), norm_enc.unsqueeze(0), dim=1)
    test_dec = F.cosine_similarity(F.normalize(model(x_test)[1], p=2, dim=1), norm_dec.unsqueeze(0), dim=1)
    # 使用解码器和编码器分别预测
    y_pred_enc = torch.where(gaussian_pos_enc.log_prob(test_enc) > gaussian_neg_enc.log_prob(test_enc), 1, 0)
    y_pred_dec = torch.where(gaussian_pos_dec.log_prob(test_dec) > gaussian_neg_dec.log_prob(test_dec), 1, 0)
    # 投票预测
    diff_enc = torch.abs(gaussian_pos_enc.log_prob(test_enc)-gaussian_neg_enc.log_prob(test_enc))
    diff_dec = torch.abs(gaussian_pos_dec.log_prob(test_dec)-gaussian_neg_dec.log_prob(test_dec))
    y_pred = torch.where(diff_enc > diff_dec, y_pred_enc, y_pred_dec)
    return y_pred,y_pred_enc,y_pred_dec

初始训练模型  
用一小部分数据来训练模型  
训练的数据来自于 online_x_train

In [12]:
# 在线学习只使用20%的数据进行训练, 80%的数据用于在线学习和更新
online_x_train, online_x_test, online_y_train, online_y_test = train_test_split(x_train, y_train, test_size=0.8, random_state=42)
# 创建张量数据集
train_dataset = TensorDataset(online_x_train, online_y_train)
# 创建数据加载器
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
# 创建一个损失函数
criterion = CRCLoss(device, tem)
# 输入维度
input_dim = x_train.shape[1]
# 创建自编码器模型
model = AE(input_dim).to(device)
# 创建优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# 调整模型进入训练模式
model.train()

AE(
  (encoder): Sequential(
    (0): Linear(in_features=196, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
  )
  (decoder): Sequential(
    (0): ReLU()
    (1): Linear(in_features=64, out_features=128, bias=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=196, bias=True)
  )
)

## 训练模型  


In [13]:
########################## 初始化训练模型 ##########################
for epoch in tqdm(range(epochs)):
    
    #  j是批次索引，data是一个元组，包含输入和标签
    for _ ,data in enumerate(train_loader,0):
        # 获取输入和标签
        inputs, labels = data # inputs.shape = (128, 206), labels.shape = (128,)
        # 将标签移动到设备上
        labels = labels.to(device)
        # 优化器梯度清零
        optimizer.zero_grad()
        # 前向传播
        enc_features, dec_features = model(inputs.to(device))     
        # 计算损失
        loss=criterion(enc_features, labels)+criterion(dec_features, labels)
        # 反向传播
        loss.backward()
        # 更新权重
        optimizer.step()
   


  0%|          | 0/300 [00:00<?, ?it/s]

In [14]:
#  将所有数据移动到设备上
# x_train = x_train.to(device)
# x_test = x_test.to(device)
online_x_train, online_y_train  = online_x_train.to(device), online_y_train.to(device)
# 克隆当前轮次的训练数据和测试数据
x_train_this_epoch, x_test_left_epoch, y_train_this_epoch, y_test_left_epoch = online_x_train.clone(), online_x_test.clone().to(device), online_y_train.clone(), online_y_test.clone()     

在线学习阶段

In [15]:
# 在线训练的过程，需要不断的测试新输入的数据，每次来一个新的数据，就需要测试一次，预测出标签，同时做一个累积，每当累积到一定数量的数据时，就需要微调模型
while len(x_test_left_epoch) > 0:
    # 如果剩余的数据少于采样间隔，则将所有剩余的数据作为这一轮的测试数据
    if len(x_test_left_epoch) < sample_interval:
        x_test_this_epoch = x_test_left_epoch.clone()
        x_test_left_epoch.resize_(0)
        y_test_this_epoch = y_test_left_epoch.clone()
        y_test_left_epoch.resize_(0)
        
    # 否则，从剩余的数据中采样一部分作为这一轮的测试数据
    else:
        x_test_this_epoch = x_test_left_epoch[:sample_interval].clone()
        x_test_left_epoch = x_test_left_epoch[sample_interval:]
        y_test_this_epoch = y_test_left_epoch[:sample_interval].clone()
        y_test_left_epoch = y_test_left_epoch[sample_interval:]
    
    # 据训练集里的正常样本的特征得出一个平均正常特征
    ## online_y_train == 0是正常样本的标签
    ## online_x_train[(online_y_train == 0)].shape   torch.Size([11190, 206]) 之所以要加squeeze()，是为了防止避免下面的情况[1,11190,206]
    ## 论文里有提到，即采用编码器的输出，也采用解码器的输出
    normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
    normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
    # 预测标签
    _,predict_label,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x_test_this_epoch, model)
    # 评估准确性
    evaluate(y_test_this_epoch, predict_label)
    
    # 随机翻转
    num_flips = int(flip_percent * len(predict_label))
    shuffle_index = np.random.choice(len(predict_label), num_flips, replace=False)
    # 翻转标签
    flip_label = predict_label.clone()
    flip_label[shuffle_index] = 1 - flip_label[shuffle_index]
    flip_label = flip_label.to(device)
    # 更新数据集
    x_train_this_epoch = torch.cat((x_train_this_epoch, x_test_this_epoch), 0)
    y_train_this_epoch = torch.cat((y_train_this_epoch, flip_label), 0)
    
    train_ds=TensorDataset(x_train_this_epoch, y_train_this_epoch)
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=True)
    
    for epoch in tqdm(range(epoch_online)):
        for _ ,data in enumerate(train_dl,0):
            inputs, labels = data
            labels = labels.to(device)
            optimizer.zero_grad()
            enc_features, dec_features = model(inputs.to(device))
            loss = criterion(enc_features, labels) + criterion(dec_features, labels)
            loss.backward()
            optimizer.step()
        

Confusion matrix
[[ 863   10]
 [ 353 1558]]
Accuracy  0.8696120689655172
Precision  0.9936224489795918
Recall  0.815279958137101
F1 score  0.8956596723196321


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 892   13]
 [ 368 1511]]
Accuracy  0.8631465517241379
Precision  0.9914698162729659
Recall  0.8041511442256519
F1 score  0.8880399647369968


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 872    9]
 [ 363 1540]]
Accuracy  0.8663793103448276
Precision  0.9941897998708844
Recall  0.8092485549132948
F1 score  0.8922363847045192


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 667  224]
 [   0 1893]]
Accuracy  0.9195402298850575
Precision  0.894189891355692
Recall  1.0
F1 score  0.9441396508728179


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 884   18]
 [ 264 1618]]
Accuracy  0.8987068965517241
Precision  0.988997555012225
Recall  0.8597236981934112
F1 score  0.9198408186469585


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 679  228]
 [   0 1877]]
Accuracy  0.9181034482758621
Precision  0.891686460807601
Recall  1.0
F1 score  0.9427423405323958


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 630  243]
 [   0 1911]]
Accuracy  0.9127155172413793
Precision  0.8871866295264624
Recall  1.0
F1 score  0.9402214022140222


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 857   22]
 [ 257 1648]]
Accuracy  0.8997844827586207
Precision  0.9868263473053892
Recall  0.8650918635170604
F1 score  0.921958041958042


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 866   34]
 [ 229 1655]]
Accuracy  0.9055316091954023
Precision  0.9798697454114861
Recall  0.8784501061571125
F1 score  0.9263923873495662


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 824   37]
 [ 216 1707]]
Accuracy  0.9091235632183908
Precision  0.9787844036697247
Recall  0.8876755070202809
F1 score  0.9310062721570767


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 838   46]
 [ 213 1687]]
Accuracy  0.9069683908045977
Precision  0.9734564339296018
Recall  0.8878947368421053
F1 score  0.928709055876686


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 882   23]
 [ 253 1626]]
Accuracy  0.9008620689655172
Precision  0.9860521528198909
Recall  0.8653539116551358
F1 score  0.9217687074829932


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 842   27]
 [ 216 1699]]
Accuracy  0.9127155172413793
Precision  0.9843568945538818
Recall  0.8872062663185378
F1 score  0.9332600933809393


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 882   25]
 [ 225 1652]]
Accuracy  0.9102011494252874
Precision  0.9850924269528921
Recall  0.880127863612147
F1 score  0.9296567248171075


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 819   36]
 [ 187 1742]]
Accuracy  0.9198994252873564
Precision  0.9797525309336333
Recall  0.9030585795749093
F1 score  0.9398435392500675


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 882   43]
 [ 195 1664]]
Accuracy  0.9145114942528736
Precision  0.9748096074985354
Recall  0.8951048951048951
F1 score  0.9332585530005608


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 831   46]
 [ 170 1737]]
Accuracy  0.9224137931034483
Precision  0.9742007851934941
Recall  0.9108547456738333
F1 score  0.9414634146341463


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 866   30]
 [ 216 1672]]
Accuracy  0.9116379310344828
Precision  0.982373678025852
Recall  0.885593220338983
F1 score  0.9314763231197771


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 848   27]
 [ 249 1660]]
Accuracy  0.9008620689655172
Precision  0.983995257854179
Recall  0.8695652173913043
F1 score  0.9232480533926585


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 833   29]
 [ 184 1738]]
Accuracy  0.9234913793103449
Precision  0.9835880022637238
Recall  0.9042663891779397
F1 score  0.9422607752778531


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 901   45]
 [ 167 1671]]
Accuracy  0.9238505747126436
Precision  0.9737762237762237
Recall  0.9091403699673558
F1 score  0.9403489026449071


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 815   42]
 [ 168 1759]]
Accuracy  0.9245689655172413
Precision  0.9766796224319823
Recall  0.9128178515827712
F1 score  0.9436695278969958


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 808   60]
 [ 181 1735]]
Accuracy  0.913433908045977
Precision  0.9665738161559888
Recall  0.9055323590814196
F1 score  0.9350579358663433


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 869   48]
 [ 166 1701]]
Accuracy  0.923132183908046
Precision  0.9725557461406518
Recall  0.9110873058382432
F1 score  0.9408185840707964


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 859   46]
 [ 199 1680]]
Accuracy  0.9119971264367817
Precision  0.9733487833140209
Recall  0.8940926024481107
F1 score  0.9320388349514563


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 823   41]
 [ 169 1751]]
Accuracy  0.9245689655172413
Precision  0.9771205357142857
Recall  0.9119791666666667
F1 score  0.943426724137931


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 804   52]
 [ 177 1751]]
Accuracy  0.9177442528735632
Precision  0.971159179145868
Recall  0.908195020746888
F1 score  0.9386223532564996


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 868   43]
 [ 193 1680]]
Accuracy  0.9152298850574713
Precision  0.9750435287289612
Recall  0.8969567538707955
F1 score  0.9343715239154616


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 830   46]
 [ 181 1727]]
Accuracy  0.9184626436781609
Precision  0.9740552735476593
Recall  0.9051362683438156
F1 score  0.9383319750067917


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 824   45]
 [ 207 1708]]
Accuracy  0.9094827586206896
Precision  0.9743297204791785
Recall  0.8919060052219321
F1 score  0.9312977099236641


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 860   56]
 [ 161 1707]]
Accuracy  0.9220545977011494
Precision  0.9682359614293817
Recall  0.9138115631691649
F1 score  0.9402368493527954


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 805   26]
 [ 209 1744]]
Accuracy  0.9155890804597702
Precision  0.9853107344632769
Recall  0.8929851510496671
F1 score  0.9368788611334945


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 878   11]
 [ 520 1375]]
Accuracy  0.8092672413793104
Precision  0.9920634920634921
Recall  0.7255936675461742
F1 score  0.8381590978360256


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 945    9]
 [ 514 1316]]
Accuracy  0.8121408045977011
Precision  0.9932075471698113
Recall  0.7191256830601093
F1 score  0.8342313787638669


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 874   13]
 [ 348 1549]]
Accuracy  0.8703304597701149
Precision  0.9916773367477593
Recall  0.816552451238798
F1 score  0.895634576467187


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 895   13]
 [ 358 1518]]
Accuracy  0.8667385057471264
Precision  0.991508817766166
Recall  0.8091684434968017
F1 score  0.8911065453478133


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 821   13]
 [ 298 1652]]
Accuracy  0.8882902298850575
Precision  0.9921921921921922
Recall  0.8471794871794872
F1 score  0.913969571230982


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 856   13]
 [ 337 1578]]
Accuracy  0.8742816091954023
Precision  0.9918290383406663
Recall  0.8240208877284595
F1 score  0.9001711351968055


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 878   14]
 [ 280 1612]]
Accuracy  0.8943965517241379
Precision  0.991389913899139
Recall  0.8520084566596194
F1 score  0.9164297896532121


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 889   22]
 [ 283 1590]]
Accuracy  0.8904454022988506
Precision  0.9863523573200993
Recall  0.8489054991991457
F1 score  0.9124820659971306


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 866    5]
 [ 356 1557]]
Accuracy  0.8703304597701149
Precision  0.9967989756722151
Recall  0.8139048614741244
F1 score  0.8961151079136691


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 863   13]
 [ 344 1564]]
Accuracy  0.8717672413793104
Precision  0.9917564996829423
Recall  0.8197064989517819
F1 score  0.8975609756097561


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 907   11]
 [ 361 1505]]
Accuracy  0.8663793103448276
Precision  0.9927440633245382
Recall  0.8065380493033226
F1 score  0.8900059136605559


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 887    9]
 [ 405 1483]]
Accuracy  0.8512931034482759
Precision  0.9939678284182306
Recall  0.7854872881355932
F1 score  0.8775147928994083


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 915   12]
 [ 372 1485]]
Accuracy  0.8620689655172413
Precision  0.9919839679358717
Recall  0.7996768982229402
F1 score  0.8855098389982111


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 865   11]
 [ 376 1532]]
Accuracy  0.8609913793103449
Precision  0.9928710304601426
Recall  0.8029350104821803
F1 score  0.8878585917125471


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 900    7]
 [ 372 1505]]
Accuracy  0.8638649425287356
Precision  0.9953703703703703
Recall  0.8018114011720832
F1 score  0.8881676010622602


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 899    3]
 [ 373 1509]]
Accuracy  0.8649425287356322
Precision  0.998015873015873
Recall  0.8018065887353879
F1 score  0.8892162639952857


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 884    8]
 [ 391 1501]]
Accuracy  0.8566810344827587
Precision  0.9946984758117959
Recall  0.7933403805496829
F1 score  0.88268156424581


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[ 898    4]
 [ 300 1582]]
Accuracy  0.8908045977011494
Precision  0.9974779319041615
Recall  0.8405951115834219
F1 score  0.9123414071510957


  0%|          | 0/3 [00:00<?, ?it/s]

Confusion matrix
[[354   2]
 [100 617]]
Accuracy  0.9049394221808015
Precision  0.9967689822294022
Recall  0.8605299860529986
F1 score  0.9236526946107785


  0%|          | 0/3 [00:00<?, ?it/s]

# 评估模型（在测试集上训练）

In [16]:
normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
x_test = x_test.to(device)
_,y_pred,_ = predict(normal_enc, normal_dec, x_train_this_epoch,y_train_this_epoch , x_test , model)
evaluate(y_test, y_pred)

Confusion matrix
[[33697  3303]
 [ 5257 40075]]
Accuracy  0.8960307049506875
Precision  0.9238554105767901
Recall  0.8840333539221742
F1 score  0.9035058054334348
