# 加载模型

导入必要的库

In [14]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch import nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
from sklearn.base import BaseEstimator, TransformerMixin
import math
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
import scipy.optimize as opt
import torch.distributions as dist
from sklearn.metrics import accuracy_score
import argparse
import warnings
from tqdm.notebook import tqdm_notebook as tqdm
from collections import defaultdict

In [15]:
warnings.filterwarnings('ignore')

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

超参数设置

In [17]:
# 超参数
tem = 0.02
bs = 128
seed = 5009
seed_round = 5
epochs = 800
epoch_online=1
sample_interval = 2784
flip_percent = 0.05

## 加载数据集

In [18]:
def get_dataset():
    train_data=pd.read_csv('en_UNSW_NB15_train.csv')
    test_data=pd.read_csv('en_UNSW_NB15_test.csv')
    y_train=train_data['label']
    y_test=test_data['label']
    X_train=train_data.drop(columns=['label'])
    X_test=test_data.drop(columns=['label'])
    normalize=MinMaxScaler()
    X_train=normalize.fit_transform(X_train)
    X_test=normalize.fit_transform(X_test)
    return X_train,y_train,X_test,y_test

In [19]:
x_train,y_train,x_test,y_test=get_dataset()
# 转换为torch张量
x_train,y_train=torch.FloatTensor(x_train).to(device),torch.LongTensor(y_train).to(device)
x_test,y_test=torch.FloatTensor(x_test).to(device),torch.LongTensor(y_test).to(device)

In [20]:
def evaluate(y,y_pred):
    y= y.cpu().detach().numpy()
    y_pred= y_pred.cpu().detach().numpy()
    # 混淆矩阵
    print("Confusion matrix")
    print(confusion_matrix(y, y_pred))
    # Accuracy 
    print('Accuracy ',accuracy_score(y, y_pred))
    # Precision 
    print('Precision ',precision_score(y, y_pred))
    # Recall
    print('Recall ',recall_score(y, y_pred))
    # F1 score
    print('F1 score ',f1_score(y,y_pred))

In [21]:
import matplotlib.pyplot as plt
def plot_loss(losses,epoch):
    plt.figure(figsize=(10,5))
    plt.title(f"{epoch} Training Loss")
    plt.plot(losses, marker='o')
    plt.xlabel("Iterations")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

## 加载模型

AE自编码器模块

In [22]:
class AE(nn.Module):
    def __init__(self, input_dim):
        super(AE, self).__init__()
        # 计算输入维度的最近的2的幂次方，比如输入维度是206，则最近的2的幂次方是128
        nearest_power_of_2 = 2 ** round(math.log2(input_dim))
        
        second_fourth_layer_size = nearest_power_of_2 // 2
        third_layer_size = nearest_power_of_2 // 4
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, third_layer_size)
        )
        self.decoder = nn.Sequential(
            nn.ReLU(),
            nn.Linear(third_layer_size, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, input_dim)
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

InfoNCE对比损失模块

In [23]:
class InfoNCE(nn.Module):
    def __init__(self, device, temperature=0.1, scale_by_temperature=True):
        super(InfoNCE, self).__init__()
        self.device = device
        self.temperature = temperature
        self.scale_by_temperature = scale_by_temperature

    def forward(self, features, labels=None):
        # 计算特征的归一化表示
        features = F.normalize(features, p=2, dim=1)
        batch_size = features.shape[0]
        num_norm = len(labels==0)
        ## contiguous方法确保张量在内存是连续存储的，因为变换视图操作需要确保张量在内存中是连续存储的
        labels = labels.contiguous().view(-1, 1) # batch_size * 1
        
        if labels.shape[0] != batch_size:
            raise ValueError('Batch size of features and labels do not match.')
        
        # 计算余弦相似度，cosine_sim[i][j]表示features[i]和features[j]的余弦相似度，矩阵大小为batch_size * batch_size
        cosine_sim = torch.nn.functional.cosine_similarity(features.unsqueeze(1), features.unsqueeze(0), dim = -1)/self.temperature
        # 将余弦相似度的对角线元素设置为0
        mask_diag = torch.eye(batch_size, dtype=torch.bool)
        cosine_sim[mask_diag] = 0
        # 正样本对
        sim_pos = cosine_sim[(labels==0).squeeze()]
        # 正样本对间的余弦相似度
        sim_pos_pos = sim_pos[:,(labels==0).squeeze()] 
        # 正样本与负样本间的余弦相似度
        sim_pos_neg = sim_pos[:,(labels==1).squeeze()]
        # 计算正样本与负样本间的分数和
        sum_pos_neg = torch.sum(torch.exp(sim_pos_neg), axis=1, keepdims=True)
        # 计算分母
        denominator = torch.exp(sim_pos_pos) + sum_pos_neg       
        loss = -(sim_pos_pos-torch.log(denominator))  
        
        
        if self.scale_by_temperature:
            loss = loss * self.temperature
        # 计算损失
        loss= loss.mean()
        return loss

## ADM自主决策

In [24]:
def gaussian_pdf(x, mean, std):
    pdf = 1/(std*np.sqrt(2*np.pi))*np.exp(-(x-mean)**2/(2*std**2))
    return pdf
def log_likelihood(params,data):
    data = data.cpu().detach().numpy()
    mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc = params
    pdf1 = gaussian_pdf(data, mean_pos_enc, std_pos_enc)
    pdf2 = gaussian_pdf(data, mean_neg_enc, std_neg_enc)
    mixture_pdf = 0.5*pdf1 + 0.5*pdf2
    log_likelihood = -np.sum(np.log(mixture_pdf))
    
    return log_likelihood
def predict(norm_enc, norm_dec, x_train, y_train, x_test, model):
    x_train_pos=x_train[(y_train==0).squeeze()]
    x_train_neg=x_train[(y_train==1).squeeze()]
    
    # 训练集全体样本编码和解码特征
    train_enc = F.normalize(model(x_train)[0], p=2, dim=1)
    train_dec = F.normalize(model(x_train)[1], p=2, dim=1)
    # 训练集正样本编码和解码特征
    train_enc_pos = F.normalize(model(x_train_pos)[0], p=2, dim=1)
    train_dec_pos = F.normalize(model(x_train_pos)[1], p=2, dim=1)
    # 训练集负样本编码和解码特征
    train_enc_neg = F.normalize(model(x_train_neg)[0], p=2, dim=1)
    train_dec_neg = F.normalize(model(x_train_neg)[1], p=2, dim=1)
    
    # 分别计算训练集正样本特征和平均正样本特征的余弦相似度 负样本同理 全体样本同理 
    sim_pos_norm_enc = F.cosine_similarity(train_enc_pos, norm_enc.unsqueeze(0), dim=1) 
    sim_pos_norm_dec = F.cosine_similarity(train_dec_pos, norm_dec.unsqueeze(0), dim=1)
    sim_neg_norm_enc = F.cosine_similarity(train_enc_neg, norm_enc.unsqueeze(0), dim=1)
    sim_neg_norm_dec = F.cosine_similarity(train_dec_neg, norm_dec.unsqueeze(0), dim=1)
    sim_all_norm_enc = F.cosine_similarity(train_enc, norm_enc.unsqueeze(0), dim=1)
    sim_all_norm_dec = F.cosine_similarity(train_dec, norm_dec.unsqueeze(0), dim=1)
    # 进行排序
    sort_sim_pos_norm_enc, indices = torch.sort(sim_pos_norm_enc)
    sort_sim_pos_norm_dec, indices = torch.sort(sim_pos_norm_dec)
    sort_sim_neg_norm_enc, indices = torch.sort(sim_neg_norm_enc)
    sort_sim_neg_norm_dec, indices = torch.sort(sim_neg_norm_dec)

    
    ## 初始化参数
    mean_pos_enc = torch.mean(sort_sim_pos_norm_enc).cpu().detach().numpy()
    std_pos_enc = torch.std(sort_sim_pos_norm_enc).cpu().detach().numpy()
    mean_pos_dec = torch.mean(sort_sim_pos_norm_dec).cpu().detach().numpy()
    std_pos_dec = torch.std(sort_sim_pos_norm_dec).cpu().detach().numpy()
    mean_neg_enc = torch.mean(sort_sim_neg_norm_enc).cpu().detach().numpy()
    std_neg_enc = torch.std(sort_sim_neg_norm_enc).cpu().detach().numpy()
    mean_neg_dec = torch.mean(sort_sim_neg_norm_dec).cpu().detach().numpy()
    std_neg_dec = torch.std(sort_sim_neg_norm_dec).cpu().detach().numpy()
    initial_params_enc = [mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc]
    initial_params_dec = [mean_pos_dec, std_pos_dec, mean_neg_dec, std_neg_dec]
    # 拟合高斯分布
    fit_enc = opt.minimize(log_likelihood, initial_params_enc, args=(sim_all_norm_enc,), method='Nelder-Mead')
    fit_dec = opt.minimize(log_likelihood, initial_params_dec, args=(sim_all_norm_dec,), method='Nelder-Mead') 
    # print("enc init")
    # print(initial_params_enc)
    # print("dec init")
    # print(initial_params_dec)
    mean1_enc, std1_enc, mean2_enc, std2_enc = fit_enc.x
    mean1_dec, std1_dec, mean2_dec, std2_dec = fit_dec.x
    # print("encoder:")
    # print(mean1_enc, std1_enc, mean2_enc, std2_enc)
    # print("decoder:")
    # print(mean1_dec, std1_dec, mean2_dec, std2_dec)
    # 选择均值小的作为正常样本的均值
    if mean1_enc < mean2_enc:
        mean_pos_enc, mean_neg_enc = mean1_enc, mean2_enc
        std_pos_enc, std_neg_enc = std1_enc, std2_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    else:
        mean_pos_enc, mean_neg_enc = mean2_enc, mean1_enc
        std_pos_enc, std_neg_enc = std2_enc, std1_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    if mean1_dec < mean2_dec:
        mean_pos_dec, mean_neg_dec = mean1_dec, mean2_dec
        std_pos_dec, std_neg_dec = std1_dec, std2_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    else:
        mean_pos_dec, mean_neg_dec = mean2_dec, mean1_dec
        std_pos_dec, std_neg_dec = std2_dec, std1_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    # gaussian_pos_enc = dist.Normal(mean1_enc, std1_enc)
    # gaussian_neg_enc = dist.Normal(mean2_enc, std2_enc)
    # gaussian_pos_dec = dist.Normal(mean1_dec, std1_dec)
    # gaussian_neg_dec = dist.Normal(mean2_dec, std2_dec)
    
    # 计算测试数据与正常样本的余弦相似度
    test_enc = F.cosine_similarity(F.normalize(model(x_test)[0], p=2, dim=1), norm_enc.unsqueeze(0), dim=1)
    test_dec = F.cosine_similarity(F.normalize(model(x_test)[1], p=2, dim=1), norm_dec.unsqueeze(0), dim=1)
    # 使用解码器和编码器分别预测
    y_pred_enc = torch.where(gaussian_pos_enc.log_prob(test_enc) > gaussian_neg_enc.log_prob(test_enc), 1, 0)
    y_pred_dec = torch.where(gaussian_pos_dec.log_prob(test_dec) > gaussian_neg_dec.log_prob(test_dec), 1, 0)
    # 投票预测
    diff_enc = torch.abs(gaussian_pos_enc.log_prob(test_enc)-gaussian_neg_enc.log_prob(test_enc))
    diff_dec = torch.abs(gaussian_pos_dec.log_prob(test_dec)-gaussian_neg_dec.log_prob(test_dec))
    y_pred = torch.where(diff_enc > diff_dec, y_pred_enc, y_pred_dec)
    return y_pred,y_pred_enc,y_pred_dec

初始训练模型  
用一小部分数据来训练模型  
训练的数据来自于 online_x_train

In [25]:
# 在线学习只使用20%的数据进行训练, 80%的数据用于在线学习和更新
online_x_train, online_x_test, online_y_train, online_y_test = train_test_split(x_train, y_train, test_size=0.8, random_state=42)
# 创建张量数据集
train_dataset = TensorDataset(online_x_train, online_y_train)
# 创建数据加载器
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
# 创建一个损失函数
criterion = InfoNCE(device, tem)
# 输入维度
input_dim = x_train.shape[1]
# 创建自编码器模型
model = AE(input_dim).to(device)
# 创建优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# 调整模型进入训练模式
model.train()

AE(
  (encoder): Sequential(
    (0): Linear(in_features=196, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
  )
  (decoder): Sequential(
    (0): ReLU()
    (1): Linear(in_features=64, out_features=128, bias=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=196, bias=True)
  )
)

## 训练模型

In [26]:
########################## 初始化训练模型 ##########################
for epoch in tqdm(range(epochs)):
    
    #  j是批次索引，data是一个元组，包含输入和标签
    for _ ,data in enumerate(train_loader,0):
        # 获取输入和标签
        inputs, labels = data # inputs.shape = (128, 206), labels.shape = (128,)
        # 将标签移动到设备上
        labels = labels.to(device)
        # 优化器梯度清零
        optimizer.zero_grad()
        # 前向传播
        enc_features, dec_features = model(inputs.to(device))     
        # 计算损失
        loss=criterion(enc_features, labels)+criterion(dec_features, labels)
        # 反向传播
        loss.backward()
        # 更新权重
        optimizer.step()
   


  0%|          | 0/800 [00:00<?, ?it/s]

In [27]:
#  将所有数据移动到设备上
# x_train = x_train.to(device)
# x_test = x_test.to(device)
online_x_train, online_y_train  = online_x_train.to(device), online_y_train.to(device)
# 克隆当前轮次的训练数据和测试数据
x_train_this_epoch, x_test_left_epoch, y_train_this_epoch, y_test_left_epoch = online_x_train.clone(), online_x_test.clone().to(device), online_y_train.clone(), online_y_test.clone()     

在线学习阶段

In [28]:
# 在线训练的过程，需要不断的测试新输入的数据，每次来一个新的数据，就需要测试一次，预测出标签，同时做一个累积，每当累积到一定数量的数据时，就需要微调模型
while len(x_test_left_epoch) > 0:
    # 如果剩余的数据少于采样间隔，则将所有剩余的数据作为这一轮的测试数据
    if len(x_test_left_epoch) < sample_interval:
        x_test_this_epoch = x_test_left_epoch.clone()
        x_test_left_epoch.resize_(0)
        y_test_this_epoch = y_test_left_epoch.clone()
        y_test_left_epoch.resize_(0)
        
    # 否则，从剩余的数据中采样一部分作为这一轮的测试数据
    else:
        x_test_this_epoch = x_test_left_epoch[:sample_interval].clone()
        x_test_left_epoch = x_test_left_epoch[sample_interval:]
        y_test_this_epoch = y_test_left_epoch[:sample_interval].clone()
        y_test_left_epoch = y_test_left_epoch[sample_interval:]
    
    # 据训练集里的正常样本的特征得出一个平均正常特征
    ## online_y_train == 0是正常样本的标签
    ## online_x_train[(online_y_train == 0)].shape   torch.Size([11190, 206]) 之所以要加squeeze()，是为了防止避免下面的情况[1,11190,206]
    ## 论文里有提到，即采用编码器的输出，也采用解码器的输出
    normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
    normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
    # 预测标签
    predict_label,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x_test_this_epoch, model)
    # 评估准确性
    evaluate(y_test_this_epoch, predict_label)
    
    # 随机翻转
    num_flips = int(flip_percent * len(predict_label))
    shuffle_index = np.random.choice(len(predict_label), num_flips, replace=False)
    # 翻转标签
    flip_label = predict_label.clone()
    flip_label[shuffle_index] = 1 - flip_label[shuffle_index]
    flip_label = flip_label.to(device)
    # 更新数据集
    x_train_this_epoch = torch.cat((x_train_this_epoch, x_test_this_epoch), 0)
    y_train_this_epoch = torch.cat((y_train_this_epoch, flip_label), 0)
    
    train_ds=TensorDataset(x_train_this_epoch, y_train_this_epoch)
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=True)
    
    for epoch in tqdm(range(epoch_online)):
        for _ ,data in enumerate(train_dl,0):
            inputs, labels = data
            labels = labels.to(device)
            optimizer.zero_grad()
            enc_features, dec_features = model(inputs.to(device))
            loss = criterion(enc_features, labels) + criterion(dec_features, labels)
            loss.backward()
            optimizer.step()
        

Confusion matrix
[[ 873    0]
 [ 696 1215]]
Accuracy  0.75
Precision  1.0
Recall  0.6357927786499215
F1 score  0.7773512476007678


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 903    2]
 [ 636 1243]]
Accuracy  0.7708333333333334
Precision  0.9983935742971888
Recall  0.6615220862160723
F1 score  0.795774647887324


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 877    4]
 [ 602 1301]]
Accuracy  0.7823275862068966
Precision  0.9969348659003832
Recall  0.6836573830793484
F1 score  0.8110972568578554


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 887    4]
 [ 575 1318]]
Accuracy  0.7920258620689655
Precision  0.9969742813918305
Recall  0.6962493396724776
F1 score  0.8199066874027994


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 900    2]
 [ 546 1336]]
Accuracy  0.8031609195402298
Precision  0.9985052316890882
Recall  0.7098831030818279
F1 score  0.8298136645962733


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 905    2]
 [ 533 1344]]
Accuracy  0.8078304597701149
Precision  0.9985141158989599
Recall  0.7160362280234417
F1 score  0.8340055848588271


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 862   11]
 [ 490 1421]]
Accuracy  0.8200431034482759
Precision  0.99231843575419
Recall  0.7435897435897436
F1 score  0.850134609632067


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 871    8]
 [ 463 1442]]
Accuracy  0.8308189655172413
Precision  0.9944827586206897
Recall  0.7569553805774278
F1 score  0.8596125186289121


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 892    8]
 [ 451 1433]]
Accuracy  0.8351293103448276
Precision  0.9944482997918113
Recall  0.7606157112526539
F1 score  0.8619548872180451


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 856    5]
 [ 388 1535]]
Accuracy  0.8588362068965517
Precision  0.9967532467532467
Recall  0.7982319292771711
F1 score  0.8865145827317354


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 874   10]
 [ 472 1428]]
Accuracy  0.826867816091954
Precision  0.9930458970792768
Recall  0.751578947368421
F1 score  0.8556021569802277


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 893   12]
 [ 364 1515]]
Accuracy  0.8649425287356322
Precision  0.9921414538310412
Recall  0.8062799361362427
F1 score  0.8896065766294774


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860    9]
 [ 362 1553]]
Accuracy  0.8667385057471264
Precision  0.9942381562099872
Recall  0.8109660574412533
F1 score  0.8932988208225482


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 901    6]
 [ 508 1369]]
Accuracy  0.8153735632183908
Precision  0.9956363636363637
Recall  0.7293553542887586
F1 score  0.8419434194341944


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 850    5]
 [ 437 1492]]
Accuracy  0.8412356321839081
Precision  0.9966599866399466
Recall  0.7734577501296008
F1 score  0.8709865732632808


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 916    9]
 [ 392 1467]]
Accuracy  0.8559626436781609
Precision  0.9939024390243902
Recall  0.7891339429800969
F1 score  0.87976011994003


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 864   13]
 [ 396 1511]]
Accuracy  0.8530890804597702
Precision  0.9914698162729659
Recall  0.7923439958049292
F1 score  0.8807927717866512


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 890    6]
 [ 422 1466]]
Accuracy  0.8462643678160919
Precision  0.9959239130434783
Recall  0.7764830508474576
F1 score  0.8726190476190476


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 867    8]
 [ 438 1471]]
Accuracy  0.8397988505747126
Precision  0.9945909398242055
Recall  0.7705605028810896
F1 score  0.8683589138134593


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 857    5]
 [ 369 1553]]
Accuracy  0.8656609195402298
Precision  0.996790757381258
Recall  0.8080124869927159
F1 score  0.8925287356321839


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 938    8]
 [ 373 1465]]
Accuracy  0.8631465517241379
Precision  0.9945689069925322
Recall  0.7970620239390642
F1 score  0.8849290244639082


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 850    7]
 [ 450 1477]]
Accuracy  0.8358477011494253
Precision  0.9952830188679245
Recall  0.766476388168137
F1 score  0.8660216945177367


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860    8]
 [ 450 1466]]
Accuracy  0.8354885057471264
Precision  0.994572591587517
Recall  0.7651356993736952
F1 score  0.8648967551622418


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 909    8]
 [ 426 1441]]
Accuracy  0.8441091954022989
Precision  0.9944789510006902
Recall  0.7718264595607928
F1 score  0.8691194209891435


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 894   11]
 [ 413 1466]]
Accuracy  0.8477011494252874
Precision  0.992552471225457
Recall  0.7802022352315061
F1 score  0.8736591179976162


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 862    2]
 [ 432 1488]]
Accuracy  0.8441091954022989
Precision  0.9986577181208054
Recall  0.775
F1 score  0.8727272727272727


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 840   16]
 [ 376 1552]]
Accuracy  0.8591954022988506
Precision  0.9897959183673469
Recall  0.8049792531120332
F1 score  0.8878718535469108


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 895   16]
 [ 320 1553]]
Accuracy  0.8793103448275862
Precision  0.9898024219247928
Recall  0.8291510945008008
F1 score  0.9023823358512493


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 863   13]
 [ 429 1479]]
Accuracy  0.8412356321839081
Precision  0.9912868632707775
Recall  0.7751572327044025
F1 score  0.87


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 861    8]
 [ 419 1496]]
Accuracy  0.8466235632183908
Precision  0.9946808510638298
Recall  0.781201044386423
F1 score  0.8751096811933314


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 901   15]
 [ 374 1494]]
Accuracy  0.8602729885057471
Precision  0.9900596421471173
Recall  0.7997858672376874
F1 score  0.8848090020728457


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 823    8]
 [ 426 1527]]
Accuracy  0.8441091954022989
Precision  0.9947882736156352
Recall  0.7818740399385561
F1 score  0.8755733944954128


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 874   15]
 [ 408 1487]]
Accuracy  0.8480603448275862
Precision  0.9900133155792277
Recall  0.7846965699208444
F1 score  0.8754783632617015


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 939   15]
 [ 394 1436]]
Accuracy  0.8530890804597702
Precision  0.9896623018607856
Recall  0.7846994535519126
F1 score  0.8753428832672966


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 876   11]
 [ 431 1466]]
Accuracy  0.8412356321839081
Precision  0.992552471225457
Recall  0.7727991565629942
F1 score  0.8689982216953172


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 893   15]
 [ 395 1481]]
Accuracy  0.8527298850574713
Precision  0.9899732620320856
Recall  0.7894456289978679
F1 score  0.8784104389086596


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 822   12]
 [ 366 1584]]
Accuracy  0.8642241379310345
Precision  0.9924812030075187
Recall  0.8123076923076923
F1 score  0.8934010152284264


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 851   18]
 [ 321 1594]]
Accuracy  0.8782327586206896
Precision  0.988833746898263
Recall  0.8323759791122716
F1 score  0.903884320952651


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 881   11]
 [ 366 1526]]
Accuracy  0.8645833333333334
Precision  0.9928432010409889
Recall  0.806553911205074
F1 score  0.8900554097404492


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 900   11]
 [ 403 1470]]
Accuracy  0.8512931034482759
Precision  0.9925725860904794
Recall  0.7848371596369461
F1 score  0.8765652951699463


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860   11]
 [ 389 1524]]
Accuracy  0.8563218390804598
Precision  0.9928338762214983
Recall  0.7966544694197596
F1 score  0.8839907192575406


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 866   10]
 [ 425 1483]]
Accuracy  0.84375
Precision  0.9933020763563295
Recall  0.7772536687631028
F1 score  0.8720964422228756


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 906   12]
 [ 379 1487]]
Accuracy  0.8595545977011494
Precision  0.9919946631087392
Recall  0.7968917470525188
F1 score  0.8838038632986627


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 878   18]
 [ 389 1499]]
Accuracy  0.8538074712643678
Precision  0.988134475939354
Recall  0.7939618644067796
F1 score  0.8804698972099854


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 911   16]
 [ 412 1445]]
Accuracy  0.8462643678160919
Precision  0.9890485968514716
Recall  0.7781367797522887
F1 score  0.8710066305003014


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 861   15]
 [ 399 1509]]
Accuracy  0.8512931034482759
Precision  0.9901574803149606
Recall  0.7908805031446541
F1 score  0.8793706293706294


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 898    9]
 [ 426 1451]]
Accuracy  0.84375
Precision  0.9938356164383562
Recall  0.7730420884389984
F1 score  0.8696433922685046


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 884   18]
 [ 359 1523]]
Accuracy  0.8645833333333334
Precision  0.9883192731992213
Recall  0.8092454835281615
F1 score  0.8898626935436751


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 879   13]
 [ 400 1492]]
Accuracy  0.8516522988505747
Precision  0.9913621262458472
Recall  0.7885835095137421
F1 score  0.8784221371798646


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 893    9]
 [ 366 1516]]
Accuracy  0.865301724137931
Precision  0.9940983606557378
Recall  0.8055260361317748
F1 score  0.8899324919283828


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[352   4]
 [105 612]]
Accuracy  0.8984156570363467
Precision  0.9935064935064936
Recall  0.8535564853556485
F1 score  0.9182295573893473


  0%|          | 0/1 [00:00<?, ?it/s]

# 评估模型（在测试集上训练）

In [29]:
normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
x_test = x_test.to(device)
y_pred,_,_ = predict(normal_enc, normal_dec, x_train_this_epoch,y_train_this_epoch , x_test , model)
evaluate(y_test, y_pred)

Confusion matrix
[[34291  2709]
 [ 7006 38326]]
Accuracy  0.8820021376864403
Precision  0.9339831850859023
Recall  0.8454513368040236
F1 score  0.8875149073141362
