# 加载模型

导入必要的库

In [1]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from torch import nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch.nn.functional as F
from sklearn.base import BaseEstimator, TransformerMixin
import math
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
import scipy.optimize as opt
import torch.distributions as dist
from sklearn.metrics import accuracy_score
import argparse
import warnings
from tqdm.notebook import tqdm_notebook as tqdm
from collections import defaultdict

In [2]:
warnings.filterwarnings('ignore')

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

超参数设置

In [4]:
# 超参数
tem = 0.02
bs = 128
seed = 5009
seed_round = 5
epochs = 800
epoch_online=1
sample_interval = 2784
flip_percent = 0.05

## 加载数据集

In [5]:
def get_dataset():
    train_data=pd.read_csv('en_UNSW_NB15_train.csv')
    test_data=pd.read_csv('en_UNSW_NB15_test.csv')
    y_train=train_data['label']
    y_test=test_data['label']
    X_train=train_data.drop(columns=['label'])
    X_test=test_data.drop(columns=['label'])
    normalize=MinMaxScaler()
    X_train=normalize.fit_transform(X_train)
    X_test=normalize.fit_transform(X_test)
    return X_train,y_train,X_test,y_test

In [6]:
x_train,y_train,x_test,y_test=get_dataset()
# 转换为torch张量
x_train,y_train=torch.FloatTensor(x_train).to(device),torch.LongTensor(y_train).to(device)
x_test,y_test=torch.FloatTensor(x_test).to(device),torch.LongTensor(y_test).to(device)

In [7]:
def evaluate(y,y_pred):
    y= y.cpu().detach().numpy()
    y_pred= y_pred.cpu().detach().numpy()
    # 混淆矩阵
    print("Confusion matrix")
    print(confusion_matrix(y, y_pred))
    # Accuracy 
    print('Accuracy ',accuracy_score(y, y_pred))
    # Precision 
    print('Precision ',precision_score(y, y_pred))
    # Recall
    print('Recall ',recall_score(y, y_pred))
    # F1 score
    print('F1 score ',f1_score(y,y_pred))

In [8]:
import matplotlib.pyplot as plt
def plot_loss(losses,epoch):
    plt.figure(figsize=(10,5))
    plt.title(f"{epoch} Training Loss")
    plt.plot(losses, marker='o')
    plt.xlabel("Iterations")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.show()

## 加载模型

AE自编码器模块

In [9]:
class AE(nn.Module):
    def __init__(self, input_dim):
        super(AE, self).__init__()
        # 计算输入维度的最近的2的幂次方，比如输入维度是206，则最近的2的幂次方是128
        nearest_power_of_2 = 2 ** round(math.log2(input_dim))
        
        second_fourth_layer_size = nearest_power_of_2 // 2
        third_layer_size = nearest_power_of_2 // 4
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, third_layer_size)
        )
        self.decoder = nn.Sequential(
            nn.ReLU(),
            nn.Linear(third_layer_size, second_fourth_layer_size),
            nn.ReLU(),
            nn.Linear(second_fourth_layer_size, input_dim)
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return encoded, decoded

CRC对比损失模块

In [10]:
class CRCLoss(nn.Module):
    def __init__(self, device, temperature=0.1, scale_by_temperature=True):
        super(CRCLoss, self).__init__()
        self.device = device
        self.temperature = temperature
        self.scale_by_temperature = scale_by_temperature

    def forward(self, features, labels=None):
        # 计算特征的归一化表示
        features = F.normalize(features, p=2, dim=1)
        batch_size = features.shape[0]
        num_norm = len(labels==0)
        ## contiguous方法确保张量在内存是连续存储的，因为变换视图操作需要确保张量在内存中是连续存储的
        labels = labels.contiguous().view(-1, 1) # batch_size * 1
        
        if labels.shape[0] != batch_size:
            raise ValueError('Batch size of features and labels do not match.')
        
        # 计算余弦相似度，cosine_sim[i][j]表示features[i]和features[j]的余弦相似度，矩阵大小为batch_size * batch_size
        cosine_sim = torch.nn.functional.cosine_similarity(features.unsqueeze(1), features.unsqueeze(0), dim = -1)/self.temperature
        # 将余弦相似度的对角线元素设置为0
        mask_diag = torch.eye(batch_size, dtype=torch.bool)
        cosine_sim[mask_diag] = 0
        # 正样本对
        sim_pos = cosine_sim[(labels==0).squeeze()]
        # 正样本对间的余弦相似度
        sim_pos_pos = sim_pos[:,(labels==0).squeeze()] 
        # 正样本与负样本间的余弦相似度
        sim_pos_neg = sim_pos[:,(labels==1).squeeze()]
        # 计算正样本与负样本间的分数和
        sum_pos_neg = torch.sum(torch.exp(sim_pos_neg))
        # 计算分母
        denominator = torch.exp(sim_pos_pos) + sum_pos_neg       
        loss = -(sim_pos_pos-torch.log(denominator))  
        
        
        if self.scale_by_temperature:
            loss = loss * self.temperature
        # 计算损失
        loss= loss.mean()
        return loss

## ADM自主决策

In [11]:
def gaussian_pdf(x, mean, std):
    pdf = 1/(std*np.sqrt(2*np.pi))*np.exp(-(x-mean)**2/(2*std**2))
    return pdf
def log_likelihood(params,data):
    data = data.cpu().detach().numpy()
    mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc = params
    pdf1 = gaussian_pdf(data, mean_pos_enc, std_pos_enc)
    pdf2 = gaussian_pdf(data, mean_neg_enc, std_neg_enc)
    mixture_pdf = 0.5*pdf1 + 0.5*pdf2
    log_likelihood = -np.sum(np.log(mixture_pdf))
    
    return log_likelihood
def predict(norm_enc, norm_dec, x_train, y_train, x_test, model):
    x_train_pos=x_train[(y_train==0).squeeze()]
    x_train_neg=x_train[(y_train==1).squeeze()]
    
    # 训练集全体样本编码和解码特征
    train_enc = F.normalize(model(x_train)[0], p=2, dim=1)
    train_dec = F.normalize(model(x_train)[1], p=2, dim=1)
    # 训练集正样本编码和解码特征
    train_enc_pos = F.normalize(model(x_train_pos)[0], p=2, dim=1)
    train_dec_pos = F.normalize(model(x_train_pos)[1], p=2, dim=1)
    # 训练集负样本编码和解码特征
    train_enc_neg = F.normalize(model(x_train_neg)[0], p=2, dim=1)
    train_dec_neg = F.normalize(model(x_train_neg)[1], p=2, dim=1)
    
    # 分别计算训练集正样本特征和平均正样本特征的余弦相似度 负样本同理 全体样本同理 
    sim_pos_norm_enc = F.cosine_similarity(train_enc_pos, norm_enc.unsqueeze(0), dim=1) 
    sim_pos_norm_dec = F.cosine_similarity(train_dec_pos, norm_dec.unsqueeze(0), dim=1)
    sim_neg_norm_enc = F.cosine_similarity(train_enc_neg, norm_enc.unsqueeze(0), dim=1)
    sim_neg_norm_dec = F.cosine_similarity(train_dec_neg, norm_dec.unsqueeze(0), dim=1)
    sim_all_norm_enc = F.cosine_similarity(train_enc, norm_enc.unsqueeze(0), dim=1)
    sim_all_norm_dec = F.cosine_similarity(train_dec, norm_dec.unsqueeze(0), dim=1)
    # 进行排序
    sort_sim_pos_norm_enc, indices = torch.sort(sim_pos_norm_enc)
    sort_sim_pos_norm_dec, indices = torch.sort(sim_pos_norm_dec)
    sort_sim_neg_norm_enc, indices = torch.sort(sim_neg_norm_enc)
    sort_sim_neg_norm_dec, indices = torch.sort(sim_neg_norm_dec)

    
    ## 初始化参数
    mean_pos_enc = torch.mean(sort_sim_pos_norm_enc).cpu().detach().numpy()
    std_pos_enc = torch.std(sort_sim_pos_norm_enc).cpu().detach().numpy()
    mean_pos_dec = torch.mean(sort_sim_pos_norm_dec).cpu().detach().numpy()
    std_pos_dec = torch.std(sort_sim_pos_norm_dec).cpu().detach().numpy()
    mean_neg_enc = torch.mean(sort_sim_neg_norm_enc).cpu().detach().numpy()
    std_neg_enc = torch.std(sort_sim_neg_norm_enc).cpu().detach().numpy()
    mean_neg_dec = torch.mean(sort_sim_neg_norm_dec).cpu().detach().numpy()
    std_neg_dec = torch.std(sort_sim_neg_norm_dec).cpu().detach().numpy()
    initial_params_enc = [mean_pos_enc, std_pos_enc, mean_neg_enc, std_neg_enc]
    initial_params_dec = [mean_pos_dec, std_pos_dec, mean_neg_dec, std_neg_dec]
    # 拟合高斯分布
    fit_enc = opt.minimize(log_likelihood, initial_params_enc, args=(sim_all_norm_enc,), method='Nelder-Mead')
    fit_dec = opt.minimize(log_likelihood, initial_params_dec, args=(sim_all_norm_dec,), method='Nelder-Mead') 
    # print("enc init")
    # print(initial_params_enc)
    # print("dec init")
    # print(initial_params_dec)
    mean1_enc, std1_enc, mean2_enc, std2_enc = fit_enc.x
    mean1_dec, std1_dec, mean2_dec, std2_dec = fit_dec.x
    # print("encoder:")
    # print(mean1_enc, std1_enc, mean2_enc, std2_enc)
    # print("decoder:")
    # print(mean1_dec, std1_dec, mean2_dec, std2_dec)
    # 选择均值小的作为正常样本的均值
    if mean1_enc < mean2_enc:
        mean_pos_enc, mean_neg_enc = mean1_enc, mean2_enc
        std_pos_enc, std_neg_enc = std1_enc, std2_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    else:
        mean_pos_enc, mean_neg_enc = mean2_enc, mean1_enc
        std_pos_enc, std_neg_enc = std2_enc, std1_enc
        gaussian_pos_enc = dist.Normal(mean_pos_enc, std_pos_enc)
        gaussian_neg_enc = dist.Normal(mean_neg_enc, std_neg_enc)
    if mean1_dec < mean2_dec:
        mean_pos_dec, mean_neg_dec = mean1_dec, mean2_dec
        std_pos_dec, std_neg_dec = std1_dec, std2_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    else:
        mean_pos_dec, mean_neg_dec = mean2_dec, mean1_dec
        std_pos_dec, std_neg_dec = std2_dec, std1_dec
        gaussian_pos_dec = dist.Normal(mean_pos_dec, std_pos_dec)
        gaussian_neg_dec = dist.Normal(mean_neg_dec, std_neg_dec)
    # gaussian_pos_enc = dist.Normal(mean1_enc, std1_enc)
    # gaussian_neg_enc = dist.Normal(mean2_enc, std2_enc)
    # gaussian_pos_dec = dist.Normal(mean1_dec, std1_dec)
    # gaussian_neg_dec = dist.Normal(mean2_dec, std2_dec)
    
    # 计算测试数据与正常样本的余弦相似度
    test_enc = F.cosine_similarity(F.normalize(model(x_test)[0], p=2, dim=1), norm_enc.unsqueeze(0), dim=1)
    test_dec = F.cosine_similarity(F.normalize(model(x_test)[1], p=2, dim=1), norm_dec.unsqueeze(0), dim=1)
    # 使用解码器和编码器分别预测
    y_pred_enc = torch.where(gaussian_pos_enc.log_prob(test_enc) > gaussian_neg_enc.log_prob(test_enc), 1, 0)
    y_pred_dec = torch.where(gaussian_pos_dec.log_prob(test_dec) > gaussian_neg_dec.log_prob(test_dec), 1, 0)
    # 投票预测
    diff_enc = torch.abs(gaussian_pos_enc.log_prob(test_enc)-gaussian_neg_enc.log_prob(test_enc))
    diff_dec = torch.abs(gaussian_pos_dec.log_prob(test_dec)-gaussian_neg_dec.log_prob(test_dec))
    y_pred = torch.where(diff_enc > diff_dec, y_pred_enc, y_pred_dec)
    return y_pred,y_pred_enc,y_pred_dec

初始训练模型  
用一小部分数据来训练模型  
训练的数据来自于 online_x_train

In [12]:
# 在线学习只使用20%的数据进行训练, 80%的数据用于在线学习和更新
online_x_train, online_x_test, online_y_train, online_y_test = train_test_split(x_train, y_train, test_size=0.8, random_state=42)
# 创建张量数据集
train_dataset = TensorDataset(online_x_train, online_y_train)
# 创建数据加载器
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
# 创建一个损失函数
criterion = CRCLoss(device, tem)
# 输入维度
input_dim = x_train.shape[1]
# 创建自编码器模型
model = AE(input_dim).to(device)
# 创建优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# 调整模型进入训练模式
model.train()

AE(
  (encoder): Sequential(
    (0): Linear(in_features=196, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
  )
  (decoder): Sequential(
    (0): ReLU()
    (1): Linear(in_features=64, out_features=128, bias=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=196, bias=True)
  )
)

## 训练模型  


In [13]:
########################## 初始化训练模型 ##########################
for epoch in tqdm(range(epochs)):
    
    #  j是批次索引，data是一个元组，包含输入和标签
    for _ ,data in enumerate(train_loader,0):
        # 获取输入和标签
        inputs, labels = data # inputs.shape = (128, 206), labels.shape = (128,)
        # 将标签移动到设备上
        labels = labels.to(device)
        # 优化器梯度清零
        optimizer.zero_grad()
        # 前向传播
        enc_features, dec_features = model(inputs.to(device))     
        # 计算损失
        loss=criterion(enc_features, labels)+criterion(dec_features, labels)
        # 反向传播
        loss.backward()
        # 更新权重
        optimizer.step()
   


  0%|          | 0/800 [00:00<?, ?it/s]

In [14]:
#  将所有数据移动到设备上
# x_train = x_train.to(device)
# x_test = x_test.to(device)
online_x_train, online_y_train  = online_x_train.to(device), online_y_train.to(device)
# 克隆当前轮次的训练数据和测试数据
x_train_this_epoch, x_test_left_epoch, y_train_this_epoch, y_test_left_epoch = online_x_train.clone(), online_x_test.clone().to(device), online_y_train.clone(), online_y_test.clone()     

在线学习阶段

In [15]:
# 在线训练的过程，需要不断的测试新输入的数据，每次来一个新的数据，就需要测试一次，预测出标签，同时做一个累积，每当累积到一定数量的数据时，就需要微调模型
while len(x_test_left_epoch) > 0:
    # 如果剩余的数据少于采样间隔，则将所有剩余的数据作为这一轮的测试数据
    if len(x_test_left_epoch) < sample_interval:
        x_test_this_epoch = x_test_left_epoch.clone()
        x_test_left_epoch.resize_(0)
        y_test_this_epoch = y_test_left_epoch.clone()
        y_test_left_epoch.resize_(0)
        
    # 否则，从剩余的数据中采样一部分作为这一轮的测试数据
    else:
        x_test_this_epoch = x_test_left_epoch[:sample_interval].clone()
        x_test_left_epoch = x_test_left_epoch[sample_interval:]
        y_test_this_epoch = y_test_left_epoch[:sample_interval].clone()
        y_test_left_epoch = y_test_left_epoch[sample_interval:]
    
    # 据训练集里的正常样本的特征得出一个平均正常特征
    ## online_y_train == 0是正常样本的标签
    ## online_x_train[(online_y_train == 0)].shape   torch.Size([11190, 206]) 之所以要加squeeze()，是为了防止避免下面的情况[1,11190,206]
    ## 论文里有提到，即采用编码器的输出，也采用解码器的输出
    normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
    normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
    # 预测标签
    _,predict_label,_ = predict(normal_enc, normal_dec, x_train_this_epoch, y_train_this_epoch, x_test_this_epoch, model)
    # 评估准确性
    evaluate(y_test_this_epoch, predict_label)
    
    # 随机翻转
    num_flips = int(flip_percent * len(predict_label))
    shuffle_index = np.random.choice(len(predict_label), num_flips, replace=False)
    # 翻转标签
    flip_label = predict_label.clone()
    flip_label[shuffle_index] = 1 - flip_label[shuffle_index]
    flip_label = flip_label.to(device)
    # 更新数据集
    x_train_this_epoch = torch.cat((x_train_this_epoch, x_test_this_epoch), 0)
    y_train_this_epoch = torch.cat((y_train_this_epoch, flip_label), 0)
    
    train_ds=TensorDataset(x_train_this_epoch, y_train_this_epoch)
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=True)
    
    for epoch in tqdm(range(epoch_online)):
        for _ ,data in enumerate(train_dl,0):
            inputs, labels = data
            labels = labels.to(device)
            optimizer.zero_grad()
            enc_features, dec_features = model(inputs.to(device))
            loss = criterion(enc_features, labels) + criterion(dec_features, labels)
            loss.backward()
            optimizer.step()
        

Confusion matrix
[[ 870    3]
 [ 469 1442]]
Accuracy  0.8304597701149425
Precision  0.9979238754325259
Recall  0.7545787545787546
F1 score  0.8593563766388558


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 903    2]
 [ 509 1370]]
Accuracy  0.8164511494252874
Precision  0.9985422740524781
Recall  0.7291112293773284
F1 score  0.8428175945862811


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 875    6]
 [ 496 1407]]
Accuracy  0.819683908045977
Precision  0.9957537154989384
Recall  0.7393589069889648
F1 score  0.8486127864897467


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 886    5]
 [ 469 1424]]
Accuracy  0.8297413793103449
Precision  0.9965010496850945
Recall  0.7522451135763338
F1 score  0.8573148705599036


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 899    3]
 [ 480 1402]]
Accuracy  0.8265086206896551
Precision  0.997864768683274
Recall  0.7449521785334751
F1 score  0.8530574992394281


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 904    3]
 [ 486 1391]]
Accuracy  0.8243534482758621
Precision  0.9978479196556671
Recall  0.7410761854022376
F1 score  0.8505044328951391


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 866    7]
 [ 472 1439]]
Accuracy  0.8279454022988506
Precision  0.9951590594744122
Recall  0.7530088958660387
F1 score  0.8573130771522193


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 873    6]
 [ 472 1433]]
Accuracy  0.8283045977011494
Precision  0.9958304378040306
Recall  0.7522309711286089
F1 score  0.8570574162679426


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 892    8]
 [ 431 1453]]
Accuracy  0.8423132183908046
Precision  0.9945242984257358
Recall  0.7712314225053079
F1 score  0.8687593423019432


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 859    2]
 [ 419 1504]]
Accuracy  0.8487787356321839
Precision  0.99867197875166
Recall  0.782111284451378
F1 score  0.8772236803732867


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 873   11]
 [ 410 1490]]
Accuracy  0.8487787356321839
Precision  0.9926715522984677
Recall  0.7842105263157895
F1 score  0.8762128785651279


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 897    8]
 [ 377 1502]]
Accuracy  0.8617097701149425
Precision  0.9947019867549669
Recall  0.7993613624268228
F1 score  0.8863971673059899


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 863    6]
 [ 413 1502]]
Accuracy  0.8494971264367817
Precision  0.9960212201591512
Recall  0.7843342036553524
F1 score  0.8775927548933684


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 902    5]
 [ 423 1454]]
Accuracy  0.8462643678160919
Precision  0.9965729952021933
Recall  0.7746403835908364
F1 score  0.8717026378896883


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 854    1]
 [ 403 1526]]
Accuracy  0.8548850574712644
Precision  0.9993451211525868
Recall  0.7910834629341628
F1 score  0.8831018518518519


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 920    5]
 [ 398 1461]]
Accuracy  0.8552442528735632
Precision  0.9965893587994543
Recall  0.7859064012910166
F1 score  0.878796992481203


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 872    5]
 [ 375 1532]]
Accuracy  0.8635057471264368
Precision  0.9967469095640858
Recall  0.8033560566334557
F1 score  0.8896631823461092


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 889    7]
 [ 380 1508]]
Accuracy  0.8609913793103449
Precision  0.9953795379537954
Recall  0.798728813559322
F1 score  0.8862768145753747


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 871    4]
 [ 459 1450]]
Accuracy  0.8336925287356322
Precision  0.9972489683631361
Recall  0.7595599790466213
F1 score  0.8623253047873922


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 853    9]
 [ 360 1562]]
Accuracy  0.8674568965517241
Precision  0.9942711648631445
Recall  0.8126951092611863
F1 score  0.8943601488691669


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 943    3]
 [ 375 1463]]
Accuracy  0.8642241379310345
Precision  0.9979536152796725
Recall  0.7959738846572362
F1 score  0.885593220338983


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 850    7]
 [ 426 1501]]
Accuracy  0.8444683908045977
Precision  0.9953580901856764
Recall  0.7789309807991697
F1 score  0.8739446870451237


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 858   10]
 [ 411 1505]]
Accuracy  0.8487787356321839
Precision  0.9933993399339934
Recall  0.785490605427975
F1 score  0.8772952491984845


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 908    9]
 [ 368 1499]]
Accuracy  0.8645833333333334
Precision  0.9940318302387268
Recall  0.8028923406534547
F1 score  0.8882962962962963


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 896    9]
 [ 409 1470]]
Accuracy  0.8498563218390804
Precision  0.9939148073022313
Recall  0.7823310271420969
F1 score  0.8755211435378202


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860    4]
 [ 376 1544]]
Accuracy  0.8635057471264368
Precision  0.9974160206718347
Recall  0.8041666666666667
F1 score  0.8904267589388697


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 851    5]
 [ 402 1526]]
Accuracy  0.8538074712643678
Precision  0.9967341606792945
Recall  0.7914937759336099
F1 score  0.8823359352413992


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 902    9]
 [ 413 1460]]
Accuracy  0.8484195402298851
Precision  0.9938733832539143
Recall  0.7794981313400962
F1 score  0.8737283064033513


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 867    9]
 [ 395 1513]]
Accuracy  0.8548850574712644
Precision  0.9940867279894875
Recall  0.7929769392033543
F1 score  0.8822157434402332


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860    9]
 [ 399 1516]]
Accuracy  0.853448275862069
Precision  0.9940983606557378
Recall  0.791644908616188
F1 score  0.8813953488372093


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 911    5]
 [ 401 1467]]
Accuracy  0.8541666666666666
Precision  0.9966032608695652
Recall  0.7853319057815846
F1 score  0.8784431137724551


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 828    3]
 [ 388 1565]]
Accuracy  0.8595545977011494
Precision  0.9980867346938775
Recall  0.8013312852022529
F1 score  0.8889520022720818


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 877   12]
 [ 387 1508]]
Accuracy  0.8566810344827587
Precision  0.9921052631578947
Recall  0.795778364116095
F1 score  0.8831625183016105


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 949    5]
 [ 407 1423]]
Accuracy  0.8520114942528736
Precision  0.9964985994397759
Recall  0.7775956284153005
F1 score  0.8735420503376304


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 878    9]
 [ 391 1506]]
Accuracy  0.8563218390804598
Precision  0.994059405940594
Recall  0.7938850817079599
F1 score  0.8827667057444314


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 899    9]
 [ 370 1506]]
Accuracy  0.8638649425287356
Precision  0.994059405940594
Recall  0.802771855010661
F1 score  0.8882335594219994


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 830    4]
 [ 412 1538]]
Accuracy  0.8505747126436781
Precision  0.9974059662775616
Recall  0.7887179487179488
F1 score  0.8808705612829324


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 860    9]
 [ 425 1490]]
Accuracy  0.8441091954022989
Precision  0.9939959973315544
Recall  0.7780678851174935
F1 score  0.8728763913298184


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 885    7]
 [ 395 1497]]
Accuracy  0.8556034482758621
Precision  0.995345744680851
Recall  0.7912262156448203
F1 score  0.8816254416961131


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 904    7]
 [ 379 1494]]
Accuracy  0.8613505747126436
Precision  0.9953364423717521
Recall  0.797650827549386
F1 score  0.8855957320687611


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 869    2]
 [ 436 1477]]
Accuracy  0.8426724137931034
Precision  0.9986477349560514
Recall  0.7720857292211186
F1 score  0.870872641509434


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 868    8]
 [ 410 1498]]
Accuracy  0.8498563218390804
Precision  0.9946879150066401
Recall  0.7851153039832285
F1 score  0.8775629759812537


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 912    6]
 [ 395 1471]]
Accuracy  0.8559626436781609
Precision  0.995937711577522
Recall  0.7883172561629154
F1 score  0.8800478612025127


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 881   15]
 [ 366 1522]]
Accuracy  0.8631465517241379
Precision  0.9902407286922577
Recall  0.8061440677966102
F1 score  0.8887591240875913


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 917   10]
 [ 407 1450]]
Accuracy  0.8502155172413793
Precision  0.9931506849315068
Recall  0.78082929456112
F1 score  0.8742839915586373


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 865   11]
 [ 390 1518]]
Accuracy  0.8559626436781609
Precision  0.9928057553956835
Recall  0.7955974842767296
F1 score  0.8833284841431481


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 902    5]
 [ 393 1484]]
Accuracy  0.8570402298850575
Precision  0.9966420416386836
Recall  0.7906233351092168
F1 score  0.8817587641117053


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 899    3]
 [ 396 1486]]
Accuracy  0.8566810344827587
Precision  0.9979852249832102
Recall  0.7895855472901169
F1 score  0.8816374962919015


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 883    9]
 [ 387 1505]]
Accuracy  0.8577586206896551
Precision  0.9940554821664465
Recall  0.7954545454545454
F1 score  0.8837345860246624


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[ 898    4]
 [ 332 1550]]
Accuracy  0.8793103448275862
Precision  0.9974259974259975
Recall  0.8235919234856536
F1 score  0.9022118742724098


  0%|          | 0/1 [00:00<?, ?it/s]

Confusion matrix
[[354   2]
 [133 584]]
Accuracy  0.8741845293569431
Precision  0.9965870307167235
Recall  0.8145048814504882
F1 score  0.896392939370683


  0%|          | 0/1 [00:00<?, ?it/s]

# 评估模型（在测试集上训练）

In [16]:
normal_enc = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[0], p=2, dim=1), dim=0)
normal_dec = torch.mean(F.normalize(model(online_x_train[(online_y_train == 0).squeeze()])[1], p=2, dim=1), dim=0)
x_test = x_test.to(device)
_,y_pred,_ = predict(normal_enc, normal_dec, x_train_this_epoch,y_train_this_epoch , x_test , model)
evaluate(y_test, y_pred)

Confusion matrix
[[34506  2494]
 [ 5941 39391]]
Accuracy  0.8975489481611039
Precision  0.9404560105049541
Recall  0.8689446748433778
F1 score  0.9032872031828657
